### ISSUE TITLE
Autoresponder has a problem

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#100]
When a user chooses the autoresponder, he can send PMs. But when someone else tries to send, reply a PMs, there is an error instead of a message.

**Comment by jojo12** [comment]
error:
1136 Column count doesn't match value count at row 1

**Comment by jojo12** [comment]
1 | () | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:138
-- | -- | --
2 | mysqli->prepare() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php:138
3 | Joomla\Database\Mysqli\MysqliStatement->__construct() | JROOT/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php:1020
4 | Joomla\Database\Mysqli\MysqliDriver->prepareStatement() | JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:1785
5 | Joomla\Database\DatabaseDriver->setQuery() | JROOT/components/com_uddeim/uddeim.php:1253
6 | uddeIMsaveMessage() | JROOT/components/com_uddeim/uddeim.php:608
7 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
8 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:218
11 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:261
12 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
14 | require_once() | JROOT/index.php:32

**Comment by slabbi** [comment]
"That error message typically means the number of values provided in the INSERT statement is bigger or smaller than the number of columns the table has, while at the same time, you did not specify the columns to be inserted. So MySQL doesn’t know which data to insert in which column and it throws back the error."

Bei
cryptmode==3
fehlt der crypthash

**Comment by slabbi** [comment]
Zeile 1242 von uddeim.php:

```
Aus
".$savedatum.", 3)";
mach
".$savedatum.", 3, '')";
```

**Comment by joomod** [comment]
danke, ich hätte jetzt einfach crypthash weggelassen

[uddeim.zip](https://github.com/user-attachments/files/16057544/uddeim.zip)

**Comment by joomod** [comment]
soll ich das im main ändern oder nachst du das?

(das ist/war aber scheinbar ein **uralt** Fehler :)

**Comment by jojo12** [comment]
can be closed!
