### ISSUE TITLE
better ux for »Use autocomplete« config

### ISSUE THREAD

**Issue by reilldesign** [slabbi/uddeIM#104]
In the backend under UddeIM Config » uddeIM Administration in the tab »Display« there is a setting option for »Use autocomplete« (Autocompleter).

However, this only works if an »Autocompleter« is selected in the »System« tab.

It took me a while to find the connection. For future users it would be desirable if these setting options were grouped together - preferably with a showon toggle.

**Comment by joomod** [comment]
you are right, but there is a third config used in the public tab (same as in display tab).
so in the **system tab** you select the JS which is used, and then if you want to use it
in normal and/or public display.

I will check if disabling the autocompleter in the system tab could be off, so a default JS 
is always selected, and you can only switch the scripts.

**Comment by joomod** [comment]
I edit the admin script, so the autocompleter in system tab has no choice for unsetting
(1st script is selected) but only will be called if set in display or public tab

- **not updated** in the main branch 
- will upload a com_uddeim package for testing soon.

**Comment by joomod** [comment]
integrated v5.6
