### ISSUE TITLE
issue in mod_uddeim when user is logged out (includes new test version 5.6 with config 2.9)

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#105]
I found an old error in the uddeim notfier module (mod_uddeim)
the error comes from the site/uddeim.php when **pfrontend is enabled**

when a user is logged out by the system (by time, so may be the static site just shows logged in)
and the ajaxcheck in the module is activated it calls uddeim.php with task **ajaxGetNewMessages**

as uddeim.php before running the task checks if pfronend is enabled and userid=0 (guest)
will result in exit this call, but running the pfrontend plugin, which means, that
in the **module output view**  a formular for a new message in raw format is displayed.

so to skip this behavior, the pfrontend check should only run if task **NOT = ajaxGetNewMessages**

after including this the result is as expected (a Note:  you are not logged in).

so I corrected the uddeim.php for this.

in the com_uddeim56 package also the two other request where included:
1) a **new config** (v2.9) where you can select if you allow prefilled text in a new message link.
2) updated autocomplete setup, so there is no more "disable" in the system tab
3) some minor changes to prevent php8.2 errors on array_intersect

[com_uddeim56_j50.zip](https://github.com/user-attachments/files/16690202/com_uddeim56_j50.zip)

**this update is not yet published in the main branch**

please test it

**Comment by jojo12** [comment]
how can I test? I want to test after all 

> a new config (v2.9) where you can select if you allow prefilled text in a new message link.

**Comment by joomod** [comment]
if you have installed and enabled in config then you can write this urls
default is this (where recip should be a valued user id)
yourpage.com/index.php?option=com_uddeim&task=new&recip=63
**now** you may write this
yourpage.com/index.php?option=com_uddeim&task=new&recip=63**&pm=a test message**

so the "a test message"should appear in the textarea input field

**Comment by jojo12** [comment]
ich schaffs nicht. Nichts erscheint. Ich bin dummy.

**Comment by jojo12** [comment]
additional:
Open new message dialog to user with username XX (this is independent from 
realname/username setting):
http://yoursite/index.php?option=com_uddeim&task=new&runame=XX 
[&nouserlist=Y]
when a user with username XX does not exist, XX is used untranslated in the input field, so 
you can also use "name 1,name 2" or "#userlist" as parameter (note: multiple recipients 
feature do not work with SEF).
nouserlist parameter (optional):
1 = suppress user list, 2 = suppress connection list, 3 = suppress both lists
add +4 when the TO field should be disabled
e.g. 4 = disable TO field only, 5 = suppress user list AND disable TO field, and so on

**Comment by jojo12** [comment]
Hi, it works fine. But a question: in the config, I have the setting to use realname. But in the PM TO field is then the username!
I think this should be changed equal to the settings.

**Comment by jojo12** [comment]
> now you may write this
/index.php?option=com_uddeim&task=new&recip=63&pm=Frage zu deinem Forumpost
you may also use bbcodes: eg. &pm=[b]Frage zu deinem Forumpost[/b]

This is not working!

**Comment by joomod** [comment]
basicly you are right with realname/username,
but the use of realname is limited to be unique.
the script checks if a realname is unique, and IF NOT
skips back to use the username,
so just look if the desired realname is not used twice or more.

**Comment by joomod** [comment]
> > now you may write this
> > /index.php?option=com_uddeim&task=new&recip=63&pm=Frage zu deinem Forumpost
> > you may also use bbcodes: eg. &pm=[b]Frage zu deinem Forumpost[/b]
> 
> This is not working!

what is not working?
just tested and the text displays
[b]Frage zu deinem Forumpost[/b]
so the bbcode is shown correctly.
(or have you test it with sending, a then there is no bold?)

**Comment by jojo12** [comment]
> basicly you are right with realname/username,
but the use of realname is limited to be unique.
the script checks if a realname is unique, and IF NOT
skips back to use the username,
so just look if the desired realname is not used twice or more.

you're right. This works!

**Comment by jojo12** [comment]
> [b]Frage zu deinem Forumpost[/b]
in the email, there is [b] and [/b] 
in the PM, it's first not bold, but when I click on it, then it gets bold.

**Comment by joomod** [comment]
> > basicly you are right with realname/username,
> > but the use of realname is limited to be unique.
> > the script checks if a realname is unique, and IF NOT
> > skips back to use the username,
> > so just look if the desired realname is not used twice or more.
> 
> you're right. This works!

you may test edit includes.db.php (line 158)
from   
`$value = $database->loadResult();`
to
`$value .= ' ['.$database->loadResult().']';`
(Notice the **.=**  !!! (dot equal)
so you will get    name [username] displayed

**Comment by joomod** [comment]
> > [b]Frage zu deinem Forumpost[/b]
> > in the email, there is [b] and [/b] , even after sending.
> > in the PM, it's first not bold, but when I click on it, then it gets bold.

I think this is quite ok for a common rarely used option :)

**Comment by jojo12** [comment]
I want to use it in JEM Eventlist for a PM to the author of an event
(Inside JEM I have now to try how I can add the event title, date and venue to make it clear for which event is the question in the PM). But I have to resolve it there. 
Thanks a lot.

**Comment by joomod** [comment]
I think your event also will have unique ID (with this you can resolve title, date etc.)
so best you lokk for this ID

**Comment by joomod** [comment]
> > what happened to your post with the add. info about runname?
> > I have it in my email, but nothing here???
> > I don't understand.
> 
> I did not use runname, I used recip=

i didn't mean for now,
but on fryday i got an email about you post explaining
add. info for the use of runame with params hiding the lists
but I didn't see this post here??

**Comment by jojo12** [comment]
Yes I remember: It was the problem: The realname is known, and in the  email and PM was username. 
even when the TO field is hidden.
So I was interested, if it is possible to hide the username (or realname) in the field to. So the email/PM goes out, without the name visible.
auf deutsch: wenn ich TO field verstecke, sieht der Ersteller der PM immer noch den usernamen, bzw. realnamen.

**Comment by joomod** [comment]
d.h. dir wäre es am liebsten wenn z'B nur die userid 
angezeigt werden würden
(ich glaube gar nichts anzeigen wäre auch irritierend)

**Comment by jojo12** [comment]
Nein, wenn ichs mir überlege, dann ist es gut so. Es kam von daher, dass wegen zweier identischer Realnamen, der username angezeigt wurde. Ich wollte nicht zusätzliche Infos rausgeben: entweder arbeite ich mit Realnamen oder Usernamen.
Sorry für das Ungemach.

**Comment by jojo12** [comment]
for me it works fine! Can be closed
