### ISSUE TITLE
Icons for answer, forward are not so clear.

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#108]
After all with smarphone:
Is it possible to add an description, if you mouse over the Icons in?

**Comment by jojo12** [comment]
the icons for recall and reply are the same! Is there no better solution?

**Comment by jojo12** [comment]
Perhaps it would  be better to use "fa-undo" for recall ?

**Comment by joomod** [comment]
basicly you are right, but in normal use you have inbox OR outbox
only in postbox this icon may confuse (on sent message it may appear as recall, on received as reply)
but I tryto switch the code for different icon (in the moment on both restore.gif is used)

which new restore/recall would you prefer:

![recallfix](https://github.com/user-attachments/assets/a762cf87-4e77-4edd-9046-eec6a7266e89)
![recall](https://github.com/user-attachments/assets/03772e25-e11a-4dbd-bc18-8d9e6e2b6f2b)
![recallx](https://github.com/user-attachments/assets/4743a126-a44c-47ed-b2e8-c5f57bdba44f)

or
![recallani](https://github.com/user-attachments/assets/0fa7c000-a137-4ae5-b327-54e6e0d9d9c9)
![restoreani](https://github.com/user-attachments/assets/9b952d0b-d262-4aee-83ae-b1a992f9733b)

**Comment by jojo12** [comment]
Nach mehr recherchieren, weiss ich viel weniger: ich dachte 'recall' meint 'zurücknehmen', also eine Botschaft, widerrufen! Also 'undo'.
Was ist jetzt gemeint?

**Comment by joomod** [comment]
ja richtig:
das icon (genannt restor.gif) steht zum einem für 
**recall** (OUTbox bzw. OUTmessage) - nur wenn noch nicht gelesen
UND für **reply** (INbox bzw. INmessage)

**Comment by joomod** [comment]
so, hab mir das script genau angeschaut und festgestellt,
dass **nur in der postbox** Ansicht ein REPLY icon auftaucht 
(das im Moment mit dem restore.gif definiert wird, also gleiches wie beim RECALL)
bei der standard INbox gibt es das gar nicht (auch nicht auf der Hilfe Seite)

d.h., um nicht alles durcheinander zu wirbeln bleiben die RECALL (=restore.gif)
bestehen und es wird lediglich ein neues reply.gif eingeführt und das icon 
im postbox script entsprechend angepasst.
wo es passt werde ich das blaue restore.gif des default template verwenden (s.o.)

**Comment by joomod** [comment]
here is the new version (based on the v5.6)
[com_uddeim561_j50.zip](https://github.com/user-attachments/files/17270325/com_uddeim561_j50.zip)

- changelog:  replaced restore.gif by reply.gif in postbox (inbox part) 
- added a reply.gif and updated restore.gif in templates

**Comment by jojo12** [comment]
Hoi, es ist klarer, aber in der Postbox erscheint nun nicht das icon, sondern 'anworten' überdeckt pm inhalt

**Comment by joomod** [comment]
welches template?

**Comment by joomod** [comment]
versuch mal den cache zu löschen.
habe alle templates noch mal gechechecked,
reply.gif überall vorhanden (so wie im script geschrieben)

**Comment by jojo12** [comment]
flatlook

**Comment by joomod** [comment]
dann hast du wahrscheinlich v5.5/5.6 nicht komplett installiert.
seit 5.5 haben die neuen templates zT. andere Namen,
(war erforderlich, um die neuen templates mit transparenten menu-gifs bei
den modulicons zu übergehen (und statt dessen FA icons zu verwenden)

flatlook/reply.gif kann er dann nicht finden

schau mal in deinen setup welche templates jetzt gelistet sind und
wähle eines davon (ich glaube flatlook ist jetzt newstyle oder newlook)
und speichere das config

**Comment by jojo12** [comment]
Danke  werde testen, nach den Ferien.

**Comment by joomod** [comment]
edit in v5.6
