### ISSUE TITLE
PageNav not working

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#11]
on my work on updating uddeIM for J5 I found that there's an error in the pagenav,
so the navigation does not work (also tested on J4 and not working)

in uddeim.php line 198 the limitstart is set by
$limitstart		= (int)uddeIMmosGetParam ($_REQUEST, 'limitstart', 0);

but the created nav links don't contain the key 'limitstart' but only the **key 'start'**

so the corrected line 198 must be
$limitstart		= (int)uddeIMmosGetParam **($_REQUEST, 'start', 0);**

**Comment by slabbi** [comment]
I am sorry but this problem is not uddeIM related: In  the code you will find: "&limitstart=".$limitstart"
So I guess that something rewrites the "limitstart" to "start" on your system.

**Comment by joomod** [comment]
oh, I didn't check the Joomla code, but how could this be on J4 and J5 ??

**Comment by joomod** [comment]
I just looked on my J3 site, 
and yes there uddeim uses $request 'limitstart' but the links came up with  **start=XX**   
but are working well, so may be something changed in J4/5 ??

**Comment by joomod** [comment]
sorry, I#m really new on github (besides reading) so I don't know about fork

**Comment by slabbi** [comment]
Is this issues corrected or reverted in the "_uddeIM5_for_Joomla5_UNSUPPORTED" now?

**Comment by joomod** [comment]
at the moment the file uddeim.php contents the "start" version.
$limitstart		= (int)uddeIMmosGetParam ($_REQUEST, 'start', 0);

on my test site i have edit it to:
$limitstart		= (int)uddeIMmosGetParam ($_REQUEST, 'limitstart', 0) ?:
                                   (int)uddeIMmosGetParam ($_REQUEST, 'start', 0);

this would accept both as long as I don't know how the limitstart/start error is effected

**Comment by joomod** [comment]
I have added a pull-request (or 2) but the first patch is wrong - can you delete this first patch?

**Comment by slabbi** [comment]
I don't see any pull request?

**Comment by joomod** [comment]
a sorry, they are just saved within my account:
https://github.com/joomod/uddeIM

I really find out how to work with github.
how must I do this here (to open a pull)?

**Comment by slabbi** [comment]
Changed it in the code now.
It is possible that you have a SEF component installed? Can you disable it and check what happens?

**Comment by joomod** [comment]
you talk about my joomla5?
no, no extra SEF plugin or component
(just what comes with Joomla)

**Comment by joomod** [comment]
I found some postings about the joomla router and sef mode,
where pagination links are exchanged limitstart <> start, eg in
siterouter.php (J5) you will find this code:
`public function buildPaginationData(&$router, &$uri)
    {
        $limitstart = $uri->getVar('limitstart');

        if ($limitstart !== null) {
            $uri->setVar('start', (int) $uri->getVar('limitstart'));
            $uri->delVar('limitstart');
        }
    }

so the limitstart is replaced by start only`

as there are more discussion about that exchange I think my
about options code would be the best and save methode to keep
the pagination running.

`$limitstart = (int)uddeIMmosGetParam ($_REQUEST, 'limitstart', 0) ?:
(int)uddeIMmosGetParam ($_REQUEST, 'start', 0);`
