### ISSUE TITLE
modules menu link changed in joomla 5.1/5.2

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#111]
as the joomla script for com_modules has changed the old menu link for modules
is no longer working as expected, so it must be changed in the manifest:
**old:** 
`<menu link="option=com_modules&amp;view=modules&amp;filter_module=0&amp;filter_search=uddeim&amp;client_id=0">UddeIM Modules</menu>`

new:
`<menu link="option=com_modules&amp;view=modules&amp;**filter[module]**=0&amp;**filter[search]**=uddeim&amp;client_id=0">UddeIM Modules</menu>`

already updated in main

**Comment by slabbi** [comment]
Joomla is really a pain in the neck. With each version it breaks compatibility.
