### ISSUE TITLE
BUG using [b] to make text bold

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#112]
If you use the [b] code to make text bold it completely strips the text between the tags...!

**Comment by joomod** [comment]
I tested it, and it works find.
assuming you use the postbox view there is a bit difference between
user -> message preview (the first line):  there is **NO formating**
when you **click** the massage (open the full text view) the **formating is shown**

![uddeimbold-notclicked](https://github.com/user-attachments/assets/68ec46a3-2bb2-4059-bef5-123098c99bf8)  
![uddeimbold-clicked](https://github.com/user-attachments/assets/9687879b-469f-4110-aef6-9a9982f842d5)

(or in copy to myself)
![uddeimbold](https://github.com/user-attachments/assets/ad3d6d08-de16-40bc-9c77-f7cd7f2ff54f)

**Comment by slabbi** [comment]
Correct. The preview cuts text so closing tags might not be present or opening tags cut.

**Comment by joomod** [comment]
seems to be a different bug, but not quite clear?
can you put it seperate and explain?
