### ISSUE TITLE
bug in postbox pagination

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#113]
I got this info from a friend:
`[The JED J5 icon thing is a general bug and is misfunctioning for all extensions I just reported it here: https://github.com/joomla/jed-issues/issues/286 Let's see what they come up with. 
in addition:
Could you please report the pagination issue in UddeIM I mentioned yesterday? It's unhandy that you can't go back further back than 20 messages.](javascript:uddeIMtoggleread("1",true);)`

_Originally posted by @jojo12 in https://github.com/slabbi/uddeIM/issues/112#issuecomment-2503106011_

**Comment by joomod** [comment]
I found that there is a missing &recip= in the pagination's queries, so 
if there are more messages they wouldn't be loaded 
is this what your friend mean?
(before solution, you can use the "show all" button to open all messages)

**Comment by joomod** [comment]
I could not find out where/why the recip iscut out when Joomla is writing the page links,
so we have to include it again:

`$shownav = str_replace("postboxuser","postboxuser&recip=".$userid,$shownav);`

then the pag links are working

replace postbox.php

[postbox.zip](https://github.com/user-attachments/files/17933550/postbox.zip)

**Comment by jojo12** [comment]
My friend tested and said, that pagination works and all files too. Thank you for this quick solution!
