### ISSUE TITLE
uddeIm ready for Joomla 5

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#12]
as I am new on github and uploads in the code section are disabled I give it a try this way:

I have recoded uddeIM v4.1 for the use with Joomla 5 (mostly the required namespace and classnames)
on my J5 testsite everything works fine (also the pagenav as I explained in my 1st issue)

in the package I removed all old uddeim library files (10-41) and added **uddeimlib50.php**,
also the library select file is deleted, so all required lib-files only link to uddeimlib50.php.

all premium addons, modules and cb2 plugins are checked and updated.
(the old **mambo** plugins are included, but **NOT updated**)

you can **download** the new J5 package here for testing, and may  be integrating here

[uddeIM_5.0-j5.zip*](https://github.com/slabbi/uddeIM/files/13323447/uddeIM_5.0-j5.zip)

*updated with new attachment.php

**Comment by slabbi** [comment]
Thanks a lot. I can create an own section for this.
But the problem you mentioned regarding the "limitstart" seems to be not uddeIM related. There is no "&start" in the code, but "&limitstart".

**Comment by joomod** [comment]
thanks a lot, and surely then the uddeim.php must be re-corrected for limitstart.
(as I stated I don't know the issue, but on J3 pagelinks with 'start=XX' are working ?)

**Comment by ManKalusch** [comment]
How do I install this version?

**Comment by ManKalusch** [comment]
How do I install this version?

**Comment by joomod** [comment]
the main component installs just using the ZIP - only on Joomla 5
(plugins and modules must be extractet first)

**Comment by ManKalusch** [comment]
Hello,
has worked so far - thank you!
Only the file dispatch gives the following error message:

`Call to undefined method Joomla\Database\Mysqli\MysqliDriver::query()`

**Comment by joomod** [comment]
sorry, haven't test so far to send messages. I will have a look.

**Comment by joomod** [comment]
can you explain when this error occurs?

**Comment by joomod** [comment]
ok, found 1st error:
in the attachment.php there is used the old $database->query(),
which must be replaced with $database->**execute**(),  (rows 130, 150, 159)
[attachment.zip](https://github.com/slabbi/uddeIM/files/13323118/attachment.zip)

**Comment by slabbi** [comment]
pushed the code to repository

**Comment by slabbi** [comment]
@joomod 
You can edit the code in the repository and create a pull request for changes.

**Comment by ManKalusch** [comment]
Perfekt, joomod! That must have been it!
It works.

**Comment by slabbi** [comment]
Added in _uddeIM5_for_Joomla5_UNSUPPORTED folder.
Please feel free to edit the code and create a pull request for fixes.
