### ISSUE TITLE
uddeIM5.0 - simple notifier module

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#13]
there have to be 2 changes:

1. in mod_uddeim_simple_notifier.php

use Joomla\CMS\Module\ModuleHelper;   must be
use Joomla\CMS\Helper\ModuleHelper;

2. in helper.php

_public function getNoMessages($userid)_   must be
public **static** function getNoMessages($userid)

**Comment by slabbi** [comment]
added
