### ISSUE TITLE
Email notification not working

### ISSUE THREAD

**Issue by crimle** [slabbi/uddeIM#14]
I am testing uddeIM with Joomla 5. It is working quite well, apart from a pretty important thing. Despite the settings (see attachment) no emails are being sent to the recipients.
![uddeIM email settings](https://github.com/slabbi/uddeIM/assets/51155809/32e4ea6c-eb3f-4e9c-af27-a00e379918ed)

Thank you and kind regards
Chris

**Comment by joomod** [comment]
hmm, 
I just tested this and it works fine.
how is your setup?  (emailer in system tab:  phpmail?)  - check this!
do not know about mosmail, thin this is erased in joomla 5

all required fields entered:  sender name + sender email?

**Comment by crimle** [comment]
Here is my current Joomla Global Configuration:
Tab «Server» > Mail > Send Mail = is set to «Yes»
I press the button [Send Test Mail] and the test email arrives.

In my UddeIM Configuration both «E-mail sender name» and «E-mail sender address» are set correctly. 

Is there a log feature that can be enabled that could help finding the wrong setting?

**Comment by joomod** [comment]
have you also check your Spam folder.
I just used the joomla test function, and emails were moved to Spam.
.
also what I asked you is the setting in **uddeim config** -> (tab) **system**
(there you can select **php mail** or mosmail, but mos may be erased)

and may be both **Uddeim and Joomla** must use the same mail system ?
(don't know, but you could test it setting Joomla also to **php mail**)

that's all I can say.
may be Slabbi can give you more informations about logs.

**Comment by crimle** [comment]
Yes, I always check the SPAM folder. 

In Uddeim Config > Tab «System» there is «php mail (Default)» selected.
In Joomla Config there is «PHP Mail» selected as well. 

Still in despair but waiting gratefully for more information. 
By the way: I am ready to donate in case this issue can be resolved.

**Comment by joomod** [comment]
hmm, may be this can help a bit to find the problem:

in the uddeim (site) file  **includes.php**  function **uddeIMsendmail**(...
at the end (row 149) remove the error depressing **@**   from 
$ret = **@**mail($tomail,$subject,$message,$header);   ->  $ret = mail(....
so that errors will be displayed (hopefully)
and try again.
you may also add  var_dump ($ret);  just before return $ret;

a 2nd error catch may be included in the main uddeim.php file
**line 1563:**
if(uddeIMsendmail($config->emn_sendername, $config->emn_sendermail, $var_toname, $var_tomail, $subject, $var_body, $replyto, $replytoname, "", $config)) {
  	// maybe a code here that the email cound not have been sent
}
**replace with:**  
try {
	uddeIMsendmail($config->emn_sendername, $config->emn_sendermail, $var_toname, $var_tomail, $subject, $var_body, $replyto, $replytoname, "", $config);
        } catch(Exception $e) {
	throw new Exception("Error sending email notification: ".$e); }

**Comment by joomod** [comment]
I have edit some uddeim files to show messages after PM is sent:
it also includes some error statements.

1. add this two lines in the germanf and english.php file
DEFINE ('_UDDEIM_MESSAGEINFO_SENT', 'Nachricht und Infomail versendet an ');
DEFINE ('_UDDEIM_MESSAGEINFO_ERROR', 'Nachricht versendet, aber Infomail fehlgeschlagen ');
(for the english language)
DEFINE ('_UDDEIM_MESSAGEINFO_SENT', 'Message and Infomail sent to ');
DEFINE ('_UDDEIM_MESSAGEINFO_ERROR', 'Message sent, but Infomail failed');

2. in **uddeimlib50**.php  function **uddeIMmosRedirect**  and function **uddeJSEFredirect**
 add these line:
**if ($msg) $app->enqueueMessage($msg);**
just before the $app->redirect  line.  (139 + 153)
this will show a message, which tells the user the message (and may be Infomail) was sent

3. in includes.php (where you may have deleted the **@** from @mail temporarely)
  now we edit the **uddeIMdispatchEMN** function, which calls the **uddeIMsendmail**

**line 908** (if(uddeIMsendmail($config->emn_sendername, $config->emn_sendermail, $var_toname, $var_tomail, $subject, $var_body, $replyto, $replytoname, "", $config)) {...

edit this line to:
**$notifmail =** uddeIMsendmail($config->emn_sendername, $config->emn_sendermail, $var_toname, $var_tomail, $subject, $var_body, $replyto, $replytoname, "", $config);
if($notifmail) {...
so we have a value if the email was sent or not.
and **after the closing** IF bracket _add the new line:_   **else return false;** (=not sent)

4. finally in the main **uddeim.php**  section _email notification_  (rows 1260 ff)
   add to the two lines which start with  **uddeIMdispatchEMN**($insID, ....);
   just a  **$notify =** uddeIMdispatchEMN(....);

and then edit the response message lines  (1310 ff)  to:
if($messageid) {  _*this is the beginning and kept untouched_
      $mosmsg=_UDDEIM_MESSAGE_REPLIEDTO;
} elseif ($notify) {  _*this is new and sent in success_
      $mosmsg=_UDDEIM_MESSAGEINFO_SENT.uddeIMgetNameFromID($savetoid, $config);
} elseif ($config->allowemailnotify && !$notify) {  _*this is also new and reports an email error_
      $mosmsg=_UDDEIM_MESSAGEINFO_ERROR.',error';
} else {   _*this is the end and also kept untouched_
      $mosmsg=_UDDEIM_MESSAGE_SENT;
}

you may edit the following function **uddeIMtoPublicSaveMessage** also,
but the above is the main function for registered users.
(just add $notify = to the   try {**$notify =** uddeIMsendmail(.....) as written in my last post.

ok, it is not a solution to get error code from the email function, but
may be after deleting the @ from mail  :)
but these messages can stay inside to show user a response after sending.

may be Slabbi can check this and I'll will post the new files?

found on stack:
_If you are on Windows using SMTP, you can use [error_get_last()]
(http://php.net/manual/function.error-get-last.php) 
when [mail()](http://php.net/manual/function.mail.php) returns false. 
Keep in mind this does not work with PHP's native mail() function._

**Comment by joomod** [comment]
as I finally got a test result with notification failed 
I checked **ALL settings - which you must DO too**.

the first setting in the email tab:  Email Benachrichtigung erlauben =  JA
**ONLY**  means that the **user can choose** wheather he wants emails or not.
(the 2nd setting is the default if an user has NOT setup this configuratiion yet. )

so please check the user settings you have selected for testing !!!

**Comment by crimle** [comment]
1.
> in the uddeim (site) file **includes.php** function **uddeIMsendmail**(... at the end (row 149) remove the error depressing **@** from $ret = **@**mail($tomail,$subject,$message,$header); -> $ret = mail(.... so that errors will be displayed (hopefully) and try again. you may also add var_dump ($ret); just before return $ret;

The file is components/com_uddeim/includes.php right? I did what you are suggesting, but no error message is being displayed.

2.
The file is components/com_uddeim/uddeim.php right? Adding the suggested code, prevents the whole page from being displayed. There is an «0 - syntax error, unexpected token "catch"». I probably made a mistake but I am unable to debug since my PHP knowledge is very poor indeed.

**Comment by crimle** [comment]
> as I finally got a test result with notification failed I checked **ALL settings - which you must DO too**.
> 
> the first setting in the email tab: Email Benachrichtigung erlauben = JA **ONLY** means that the **user can choose** wheather he wants emails or not. (the 2nd setting is the default if an user has NOT setup this configuratiion yet. )
> 
> so please check the user settings you have selected for testing !!!

The screenshot shows my settings in the E-Mauil tab.
![uddeIM-E-Mail-Settings](https://github.com/slabbi/uddeIM/assets/51155809/c6e149a0-eaa3-4d8f-b76f-06cac0d21f02)

**Comment by slabbi** [comment]
This is *not* the setting in the email tab. This is the admin backend, not the user frontend.
In the backend you can go to the userlist and check what settings the user has set.

**Comment by crimle** [comment]
> This is _not_ the setting in the email tab. This is the admin backend, not the user frontend. In the backend you can go to the userlist and check what settings the user has set.

This one?
![E-Mail-Benachrichtigung](https://github.com/slabbi/uddeIM/assets/51155809/cde6691c-5e2d-4f87-9e29-6f85eb20a025)

**Comment by crimle** [comment]
> I have edit some uddeim files to show messages after PM is sent: it also includes some error statements.

I am getting a «0 - Undefined constant "_UDDEIM_MESSAGEINFO_ERROR"»
Sorry for being so awkward. PHP is like double-dutch for me.

**Comment by slabbi** [comment]
Yes, or this one:
![admin_d_usersettings](https://github.com/slabbi/uddeIM/assets/65805263/7700a806-c6cb-4bdb-94e4-860f4cd844b4)

**Comment by joomod** [comment]
> > I have edit some uddeim files to show messages after PM is sent: it also includes some error statements.
> 
> I am getting a «0 - Undefined constant "_UDDEIM_MESSAGEINFO_ERROR"» Sorry for being so awkward. PHP is like double-dutch for me.

this error is like you have not updated the language file (english +) german
_UDDEIM_MESSAGEINFO_ERROR is a new string added by me.

for the user settings Slabbi showed you (the right) view in old Joomla.
in J5 backend it will look like this
![uddeim5](https://github.com/slabbi/uddeIM/assets/149375504/523ba45f-bd30-43d7-8d36-e732cd6cb488)

dont' look at the tabs, you go to the user settings from the top buttons
![uddeim5b](https://github.com/slabbi/uddeIM/assets/149375504/66f1e4c5-38fe-4598-869d-37aa03f47d68)

but to get a bit clearer, please tell us how you have tested.
- when you get the catch error it means that you have tried to send a message from 
- a public user, because the new try ... catch line only is in the uddeIMtoPublicSaveMessage
- function. (I posted the try - catch too fast :(  the main function is uddeIMsaveMessage)

so please 1st tell us how you have tested, and/or try to send from reg.user to reg.user

btw.  um es uns etwas einfacher zu machen könnten wir auch in deutsch schreiben :)

**Comment by crimle** [comment]
> btw. um es uns etwas einfacher zu machen könnten wir auch in deutsch schreiben :)
👍 Ich habe mit einem registrierten und eingeloggten Test-Account eine Nachricht an meinen normalen-Account gesendet. Dabei ist beim Senden die erwähnte Fehlermeldung aufgetreten.

**Comment by joomod** [comment]
wg. dem catch error:
bitte mal überprüfen ob alle Klammern gesetzt sind:
`try {`
         $notify = uddeIMsendmail($config->emn_sendername, $config->emn_sendermail,....usw.
`} catch(Exception $e) {`
	throw new Exception("Error sending email notification");
`}`

wenn Du mit einen reg. User die Nachricht gesendet hast dürfte die try...catch gar nicht aufgerufen werden (außer php hat den kompletten code geprüft und einen Fehler gefunden)

**Comment by joomod** [comment]
und gem. Deiner Erklärung: wie ist die user Einstellung bei Deinem normalen account?

**Comment by joomod** [comment]
hab gerade mal die public mail funktion getested, und auch da klappt der email Versand

**Comment by joomod** [comment]
kleiner Tip:
ich habe gerade die **admin.uddeim.php** geändert, damit die geänderten Einstellungen
nach dem Seiten reload direkt sichtbar sind (opcache_reset();).
lade dir doch diese neue Version herunter, damit die reelen Einstellungen sichtbar sind

**Comment by crimle** [comment]
> und gem. Deiner Erklärung: wie ist die user Einstellung bei Deinem normalen account?
Genau gleich

**Comment by crimle** [comment]
Wenn ich die Fehlermeldung «0 - Undefined constant "_UDDEIM_MESSAGEINFO_ERROR"» mit einem Neuladen der Seite übergehe, erschein eine Fehlermeldung 
«**CSRF Angriff erkannt**»
![CSRF Angriff erkannt](https://github.com/slabbi/uddeIM/assets/51155809/0db009c2-03d5-4e62-8595-b9c40c4d5693)

**Comment by joomod** [comment]
ich such gerade ann diese Meldung ausgelöst wird
(möglicherweise durch den reload?)
kannst Du nicht die Sprachdateien ergänzen?
(german**f**.php
DEFINE ('_UDDEIM_MESSAGEINFO_SENT', 'Nachricht und Infomail versendet an ');
DEFINE ('_UDDEIM_MESSAGEINFO_ERROR', 'Nachricht versendet, aber Infomail fehlgeschlagen ');
(english.php)
DEFINE ('_UDDEIM_MESSAGEINFO_SENT', 'Message and Infomail sent to ');
DEFINE ('_UDDEIM_MESSAGEINFO_ERROR', 'Message sent, but Infomail failed');

andere Frage: ist dein System schon öffentlich oder kannst du mir den
backend Zugang geben?

**Comment by crimle** [comment]
Die Sprachdateien sind wirklich ergänzt: 
administrator/components/com_uddeim/language/english.php
administrator/components/com_uddeim/language/germanf.php
administrator/components/com_uddeim/language/germani.php
Es ist mir ein Rätsel, warum dies ohne Wirkung ist. 
Back-End-Zugang kann ich Dir gerne verschaffen. Wohin soll ich die Zugangsdaten senden?

**Comment by joomod** [comment]
probier mal unter uddeim backend -> tab system den CSRF Schutz zu deaktivieren
und schau mal was dann passiert.
Daten kannst Du mir senden an:  
joomod@gmx-topmail.de

**Comment by crimle** [comment]
CSRF Schutz ist deaktiviert. Nach dem Senden erscheint wieder «Undefined constant "_UDDEIM_MESSAGEINFO_ERROR"». Neu ist, dass das Neuladen der Seite keine Änderung mehr bewirkt. Es bleibt «Undefined constant "_UDDEIM_MESSAGEINFO_ERROR"». Vorher kam ich zurück zur Seite «Private Nachrichten».

Back-End-Zugang folgt.

**Comment by joomod** [comment]
danke.
ich stell mal mein system um (im Moment verwende ich die Postbox und habe popups deaktiviert) und teste das mal.
wie ist denn dein Testaccount Name, damit ich mal probieren kann.

vielleicht kannst Du mir in der Zwischenzeit mal folgende Dateien per mail senden:
(am besten zusammen - gezippt)
germanf.php
english.php
uddeim.php
includes.php
admin.uddeim.php

**Comment by crimle** [comment]
Mein richtiger Benutzername ist crimleit, mein Testaccount crimleittest. Gewünschte Dateien liegen bei. 
[uddeim.zip](https://github.com/slabbi/uddeIM/files/13853824/uddeim.zip)

**Comment by joomod** [comment]
so, nur für mich :) gute Nachrichten:
also auf meinem System funktioniert alles auch ohne Postbox und mit Popup
(schade, dachte die Popup Variant blockiert vielleicht die emails)

verwirrend ist auch, dass **mein System Deine** germanf.php problemlos liest

**Comment by joomod** [comment]
sorry, mußte mich um meine Klinikbuchung kümmern.
mache morgen weiter

**Comment by joomod** [comment]
die Sprachdateien funktionieren jetzt
(mußten im language.utf8 Verzeichniss gespeichert werden)
.
ich hab mal den Phoca Commander installiert, damit ich Zugriff auf die
Dateien habe (so konnte ich die Sprachdateien kopieren)
kannst Dir ja mal anschauen oder später wieder löschen
(ich hab es so eingestellt, dass nur Super-User Zugriff darauf haben)

**Comment by joomod** [comment]
hab mal über div. debug Eiträge folgende Fehlermeldung (aus dem mail Versand) bekommen.
`'joomla/database', '2.2.0', 'The parameter $new is deprecated and will be removed in 4.0, use %s::createQuery() instead.',`
in einer erweiterten debug version kommt als Quelle leider nur Symphony-deprecation-contracts.
keine Ahnung was diese fraework genau macht und wie/ob man es abstellen kann.
Im Moment bin ich etwas ratlos :(

**Comment by crimle** [comment]
symfony scheint wichtig zu sein. Als ich testhalber den Ordner libraries/vendor/symfony umbenannt habe in libraries/vendor/symfony-OLD funktionierte die ganze Website nicht mehr (weisse Seite).

**Comment by joomod** [comment]
hallo,
ja, Symfony ist von Joomla fest eingebunden für div. Features u.a. für besondere Fehlermeldungen.
das blöde ist nur, dass ich dann bei der Meldung eben nur die Zeile/Datei von Symfony angezeigt
bekomme (als auslösende), aber eben nicht die eigentlich Fehlerquelle :(

**Comment by crimle** [comment]
Sollte ich mal von PHP-Mail auf SMTP umstellen?

**Comment by joomod** [comment]
weis nicht - Versuch macht kluch  :)

auf alle Fälle kannst Du / wollte ich mal probieren in der Joomla datei
den Fehler Aufruf auszukommentieren:
DatabaseDriver.php (libraries/vendor/joomla/database/src/)  
public function getQuery($new = false) 
und hier im IF($new)  die Zeile /* trigger_deprecation( ... ); */
so dass nur noch  return $this->createQuery();  aktiv bleibt.

Symfony schreibt ja selber:  (würde dann sogar alles ausschalten)
_While not recommended, the deprecation notices can be completely ignored by declaring an empty function trigger_deprecation() {} in your application._

**Comment by crimle** [comment]
Auf SMTP umstellen brachte keinen Erfolg. 

> auf alle Fälle kannst Du / wollte ich mal probieren in der Joomla datei den Fehler Aufruf auszukommentieren: DatabaseDriver.php (libraries/vendor/joomla/database/src/) public function getQuery($new = false) und hier im IF($new) die Zeile /* trigger_deprecation( ... ); */ so dass nur noch return $this->createQuery(); aktiv bleibt.

Wenn ich das tue, gibt es einen Totalausfall
**Es ist ein Problem aufgetreten.**
**Der Server lieferte ein "500 - Whoops, looks like something went wrong."**

**Comment by joomod** [comment]
ooops, - komisch.
ich probier es später trotzdem nochmal mit SMTP und der debug version
(es stand ja irgendwo, dass last_error nur bei SMTP funktioniert bzw. nur dann einen email
Fehler anzeigt. Kann ja sein, dass der database error nur der letzte erfasste Fehler ist und
gar nichts mit dem email Versuch zu tun hat.)

**Comment by joomod** [comment]
also ich glaube der database Fehler kann nicht das Problem sein, denn
1. gibt es in UddeIM kein getQuery('true')
2. sind in **Joomla5** selbst **980** Treffer
   schon komisch, auf der einen Seite schreiben sie veraltet und wird in vers4 (der Datenbank) 
    gelöscht, aber selber verwenden sie es noch und Joomla ist voll davon ?????

**Comment by crimle** [comment]
Soeben sind 6 Mails hereingekommen! Es scheint jetzt plötzlich zu funktionieren!

**Comment by joomod** [comment]
JA, jetzt müßte es gehen.
das Problem waren die Zeichen für **new line** im Header
das script verwendet "nur" `\n` aber der betreffende Server verlangt `\r\n`

also für alle die mit dem email Versand Probleme haben einfach mal beide Varianten test
(vielleicht ergänze ich die admin.uddeim.php um die Option:  `verwende \r\n`)

**Comment by joomod** [comment]
added email debug and force \r\n to setup and site code
so now you can check whats going with your php email
