### ISSUE TITLE
uddeIM for Joomla 5: error when saving settings

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#27]
0 Call to undefined function opcache_reset() 

1 | () | JROOT/administrator/components/com_uddeim/admin.uddeim.php:460
-- | -- | --
2 | uddeIMsaveSettings() | JROOT/administrator/components/com_uddeim/admin.uddeim.php:384
3 | require_once() | JROOT/administrator/components/com_uddeim/uddeim.php:17
4 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
5 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
6 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
11 | require_once() | JROOT/administrator/index.php:32

**Comment by joomod** [comment]
should be fixed - dl the new admin.uddeim.php
or just add **if (function_exists('opcache_reset'))**  before the opcache_reset()

`if (function_exists('opcache_reset'))
 opcache_reset();`
