### ISSUE TITLE
Email subject seems to be special

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#29]
Hi,
When I compare the actual uddeim email "subject" and "from" with normal notification emails, the SPAM problem could be there
I've set only: 
`info@folk-tanz.ch `
like in joomla and everywhere.
the from writes:
`"info@folk-tanz.ch" Organization: folk-tanz.ch User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.8.1.6) Gecko/20070728 Thunderbird/2.0.0.6 MIME-Version: 1.0 Content-type: text/plain <info@folk-tanz.ch>`
and the subject is:
`Nachrichten für Sie auf folk-tanz.ch`
in the normal from there is only:
`info@folk-tanz.ch`
and the subject is:
`folk-tanz.ch: Test aus Kontakt JEM`
EDIT: and the special thing is: even if I don't use Mozilla, there is this line

EDIT2: after all look at the **quotation marks**:
 in all other emails there are no quotation marks in "from"

**Comment by joomod** [comment]
the header line are set fixed by the script:
	$header  = "From: ".$temp." <".$frommail.">\n";
	$header .= "Organization: ".$mosConfig_sitename."\n";
	**$header .= "User-Agent: Mozilla/5.0 (Windows; U; Windows NT 6.0; en-US; rv:1.8.1.6) Gecko/20070728 Thunderbird/2.0.0.6\n";
	$header .= "MIME-Version: 1.0\n";
	$header .= "Content-type: text/plain;** charset=".uddeIMgetCharsetMailalias($config->mailcharset)."\n";
	$header .= "Content-Transfer-Encoding: 8bit\n";

if you prefer, you may edit this lines.

subject comes from the germanf.php file -> DEFINE ('_UDDEIM_EMN_SUBJECT',
(I have edited this to "neue Nachricht auf %site% to avoid encoding problem)

**Comment by jojo12** [comment]
thanks , but where is this script   I looked in script50.php, no such

**Comment by joomod** [comment]
includes.php

**Comment by slabbi** [comment]
Seems to be a local problem with spam filtering.
The header lines from https://github.com/slabbi/uddeIM/issues/29#issuecomment-1882809044 are important to have a correct character encoding (except User-Agent).
