### ISSUE TITLE
mod_uddeim_mailbox50 special sign when using postbox plugin

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#30]
When I set use postbox plugin, I get some special signs in the view:
```
Postbox
↓ 3 &nerr; 0
```
what does it mean or how to make it clear?

**Comment by joomod** [comment]
hmm, don't know where I got it, but should be the code for north-east-arrow.
replace it (in mod_uddeim_mailbox.php - line 139) with &#8599; for north-east or simply &uarr; for uparrow.  (in your example you have 3 in inbox  and 0 in outbox)

**Comment by joomod** [comment]
haha, github replaced it:  &#8599 ; (northeast)  &uarr ; (uparrow)
