### ISSUE TITLE
J4: Pressing "Delete all" button with no message selected leads to ugly error page

### ISSUE THREAD

**Issue by codeling** [slabbi/uddeIM#31]
With the current master version on joomla 4, if on the uddeIM page I select no message and press the "Delete All" button on the lower left, an error page opens, with message
```
count(): Argument #1 ($value) must be of type Countable|array, null given
```

This should be caught and a nice error message be shown instead (e.g., "Please select a message first!").

Note: I'm planning to look into this myself, unless somebody else is faster :)

**Comment by joomod** [comment]
you are right, it's scince php8 not allows count on empty values.
I edit my v5 version - (and look if I'm allowed to do so in the v4 version)

**Comment by joomod** [comment]
v4 and v5 corrected (use empty())

**Comment by codeling** [comment]
@joomod thanks a lot for the quick response and fix!
