### ISSUE TITLE
Rename "mosMail" to "Joomla mail", and make default

### ISSUE THREAD

**Issue by codeling** [slabbi/uddeIM#32]
I noticed that as far as I can tell, uddeIM uses php's `mail` function for sending email notifications; my expectation would have been that uddeIM uses the way to send mails configured in Joomla's main configuration.

I find this surprising and a bit annoying - it means that for any site, I need to make sure that *both* the Joomla configuration as well as the php mail configuration are set up correctly. Not having done much work yet with php's mail function, I also don't see an obvious way at the moment to configure an SMTP connection with authentication there [in php's documentation on that subject](https://www.php.net/manual/en/mail.configuration.php).

Is there a good argument why uddeIM doesn't simply use Joomla's built in mailing capabilities?

**Comment by codeling** [comment]
I see now that there currently are two backends implemented for sending emails, "mosMail" and and "php mail".

My recomendation would be to implement a third one "Joomla mail" and make it default. If I have some time I can try and look into this in the next days!

**Comment by slabbi** [comment]
uddeIM uses to functions:
"mosMail" -> uses Joomla way to send messages (for historical reasons it is called mosMail)
"mail" -> uses php's mail function

**Comment by codeling** [comment]
Thanks for the clarification!

Would it maybe make sense to rename it to "Joomla mail" and make it the default?

**Comment by slabbi** [comment]
I do not longer support uddeIM (see my email @Joomlapolis).
You can create a pull request. The text can be found in the language files, the defaults in the config class.

**Comment by codeling** [comment]
> You can create a pull request. The text can be found in the language files, the defaults in the config class.
I plan to do so, and thanks for the pointers!

**Comment by joomod** [comment]
I replaced mosMail in "my" J5 version

**Comment by slabbi** [comment]
Yes, in pre-J5 versions there is no change necessary since these version will be orphaned soon.

**Comment by codeling** [comment]
> I replaced mosMail in "my" J5 version

Good to know, didn't have the chance yet to test on J5 but will do so soon. Is Joomla mail also the default already?

> Yes, in pre-J5 versions there is no change necessary since these version will be orphaned soon.

J 4.4 [is supported until October of 2025](https://docs.joomla.org/Special:MyLanguage/Joomla!_CMS_versions), I wouldn't call this soon ;).

**Comment by slabbi** [comment]
Let's see how often they break backward compatibility in that branch until then.

**Comment by joomod** [comment]
> Is Joomla mail also the default there already?

No, because I  added some debug options in php mail, so php stays default,
but what is default?
as there is no fallback function, default is simply what is in the config file on a new installation,
and changing is one simple click (Jommla itself uses php mail as 1 of 3 options, because
you don't need additional settings as for smpt)
If you wish to change you simply must edit config.class.php and change var **$mailsystem = 1**;
