### ISSUE TITLE
Warnings in Joomla 5.0.3

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#33]
When error debug= maximum, I get:

Warning: Undefined variable $versionstring in mysite.ch/components/com_uddeim/uddeim.php on line 317

and

Warning: Undefined variable $versionstring in mysite/components/com_uddeim/uddeim.php on line 718

possible solution: add at the beginning
`$versionstring = '';`

uddeim for Joomla 5 works fine, thank you for your efforts
Jojo

**Comment by joomod** [comment]
I saw I have forgotten to included the **global line for $versionstring** in uddeim.php on github.
now it is fixed and warning should be gone

**Comment by jojo12** [comment]
solved in RC1, thanks
