### ISSUE TITLE
Error in notifier with Ajax when postbox in CB open

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#34]
in joomla 5 uddeim 5 RC1:

when a user has a new PM it shows name(and teaser). After opening the inbox and seeing the message, the ajax changes the module and shows:
Private Nachrichten

neue Nachrichten
Oops!
Seite nicht gefunden

Während der Anfrage ist ein Fehler aufgetreten.

even when debug=on and error reports=maximum no more details

I am using uddeIm with premium and cb (setting for using with uddeIM!

**Comment by joomod** [comment]
I try to find out, 
so this belong to simple_notifier  or the mod_uddeim notifier?

**Comment by jojo12** [comment]
It's the mod_uddeim notifier

**Comment by joomod** [comment]
trying to find out I came across a basic link error - missing item_id (as used in mod_uddeim and even in the main uddeim menubar) so the the linked pages are not shown well.
can you please check this too (may be it is an error in my menu setup and not in uddeim)

in the uddeim_notifier I got a working, but partial link (item_id missing) so far,
but not shure if ajax was working right. (got the same link without ajax)

**Comment by jojo12** [comment]
sorry, I don't understand what you want to know, but here what I get:

`•  SELECT COUNT(id) FROM `xxxxx_menu` WHERE link LIKE '%com_uddeim%' AND published=1 AND access<=2 AND language IN ('de-DE','*') LIMIT 1


•  SELECT g.id AS gid FROM (xxxxx_users AS u INNER JOIN `xxxxx_user_usergroup_map` AS um ON u.id=um.user_id) INNER JOIN `xxxxx_usergroups` AS g ON um.group_id=g.id WHERE u.id=784
`

this is always repeated when ajax is on.

this is after I've read a new message (this was shown before), then it starts with the 
`neue Nachrichten
Oops!
Seite nicht gefunden`

**Comment by jojo12** [comment]
when Ajax is off, then it shows:
`Private Nachrichten

keine neuen Nachrichten`

**Comment by joomod** [comment]
so the ajax error appears when there are **no new** messages  - ok I look at this now :)

my issue about the links came from the uddeIMgetItemid() function.
(I know or found out, that there is an option to overwrite itemid to fix the used itemid for this, but I just try to find out if there is an error in the logic - as far as I understand this logic)

as you see in your sql query there is access<=2  (2 is standard joomla regged level),
but gid = 2 belongs to special usergroup like admins (I think also you).

basic regged users would be gid=1, so if menu->uddeim items are set to registerd (=level 2)
no entry will be found, although the user is registerd (by where access<=1).

I don't know if Joomla has changed the viewlevel numbering since v1.6, 
as this sql condition comes from old uddeim

**- may be Slabbi can help please ?**  (just being confused)

so can you try (with no overwrite settings) if you got correct links in the module and uddeim menu when logged in as normal regged user  (not as admin)

**Comment by jojo12** [comment]
sorry, I am confused too :-(

**Comment by joomod** [comment]
just test uddeim when logged in as **standard user** (not admin)
and see how the links in the mod_uddeim and uddeim menu are generated.

In my case they come ending with &itemid=0 which leads to load the clicked
uddemim link not in the normal way (site) but in the frontpage.

**Comment by jojo12** [comment]
this is from a only registrated user:
`•  SELECT g.id AS gid FROM (xf910_users AS u INNER JOIN `xxxxx_user_usergroup_map` AS um ON u.id=um.user_id) INNER JOIN `xxxxx_usergroups` AS g ON um.group_id=g.id WHERE u.id=786
180μs536B/components/com_uddeim/uddeimlib50.php:401Copy
•  SELECT g.id AS gid FROM (xxxxx_users AS u INNER JOIN `xxxxx_user_usergroup_map` AS um ON u.id=um.user_id) INNER JOIN `xxxxx_usergroups` AS g ON um.group_id=g.id WHERE u.id=786
182μs536B/components/com_uddeim/uddeimlib50.php:401Copy
•  SELECT COUNT(id) FROM `xxxxx_menu` WHERE link LIKE '%com_uddeim%' AND published=1 AND access<=1 AND language IN ('de-DE','*') LIMIT 1
665μs536B/components/com_uddeim/includes.db.php:292Copy
`

**Comment by jojo12** [comment]
I don't know where to look

**Comment by joomod** [comment]
I'm nearly finshed with the ajax error
(my site keeps without error and ajax enabled)
you may try the att. file.
(the error was created by an invalid class check and otherwise fall back 
to the old joomla **index2.php** call, which doesn't exists anymore)

[mod_uddeim.php.zip](https://github.com/slabbi/uddeIM/files/14409885/mod_uddeim.php.zip)

your check is fine, and look at the 3rd sql query which contains **AND access<=1** ,
so if you have set uddeim for registerd only the menu entries will have access=2
and therefore no menu-entries and itemid could be found.
now simply look at the generated links in the uddeim top menu (just move the mouse over some)
(inbox-trash-archive-contact-new etc.) - if uddeim is for regged only (as in my case) all links
ends with **&itemid=0**  - please check this.

**Comment by jojo12** [comment]
Interesting:
When it is now on the home/start site, then it seems ok,
when I go to the mailbox, then it starts with "Seite nicht gefunden". But now it says:
`neue Nachrichten
Oops!
Seite nicht gefunden

Während der Anfrage ist ein Fehler aufgetreten.`
when there is no IM

**Comment by joomod** [comment]
hmm, I have enabled now on the uddeim site too, but got no errors.
must look deeper tomorrow.
(ach ja, wir sollten auf deutsch weitermachen :)

**Comment by joomod** [comment]
hopefulle solved in new RC2 (see releases)

**Comment by jojo12** [comment]
Es kommt noch, aber nur via CB2 wenn ich ins CB Profil gehe.

**Comment by jojo12** [comment]
Es muss cb_inbox sein, weil der Fehler nur dann kommt, wenn cb_inbox aktiviert ist!

**Comment by joomod** [comment]
ja, hab es gefunden und soweit angepasst.
Habe übersehen, dass in pms_uddeim_inbox eine eigenständige Funktion läuft, 
die die uddeim item_id ausliest und wenn die falsch ist (zB die item_id von CB) dann
findet ajax die Seite nicht.
probiers mal damit
[pms.showinbox.zip](https://github.com/slabbi/uddeIM/files/14486360/pms.showinbox.zip)

ansonsten lade ich gleich eine geänderte RC2 hoch.

**Comment by jojo12** [comment]
im Profil kommt der Fehler immer noch, aber in der inbox nicht mehr

**Comment by joomod** [comment]
ich such mal weiter.
dumm nur, dass bei mir gar nix dergleichen kommt.

**Comment by joomod** [comment]
kannst Du mal testweise in der uddeim Config (system) das overwrite item_id 
aktivieren und die item_id (menu id) deines uddeim eintragen?

**Comment by jojo12** [comment]
Es war zwar schon eingetragen aber nicht aktiviert (ja). dann cache cleaner. Aber das Problem bleibt.
[Ich selber schalte die Meldungen ab, so dass nur die Meldung links oben kommt, aber beim Prüfen melde ich alles. Ich hoffe, das ist ok so?]

**Comment by jojo12** [comment]
wenn ich das Private Messaging System (uddeIM PMS) in CB deaktiviere, kommt das Problem nicht, obwohl ich Zugang zu den PMs habe. Ist es möglich, dass das Problem dort liegt (es hat dort auch item_id suche)?

**Comment by jojo12** [comment]
siehe problem "Starke Verschlüsselung:
Interessant: wenn ich Verschlüsselung "Starke Veschlüsselung" abschalte, (ich habe nun base64 gewählt), dann kommt das Problem "Seite nicht gefunden" nicht mehr!
Kannst Du mal versuchen, "starke Verschlüsselung" zu verwenden

**Comment by joomod** [comment]
ok, die Verschlüsselung in Uddeim:  bei mir ist **keine** eingestellt
deshalb bekomme ich wohl keine Fehler - 
muß also im code mal nach den versch. encryt modes schauen

**Comment by jojo12** [comment]
Kannst du mir deine email schicken?

**Comment by joomod** [comment]
gibts hier (github) sowas wie ein PM system?
hab da noch nix gefunden

**Comment by jojo12** [comment]
![Seitenichtgefunden](https://github.com/slabbi/uddeIM/assets/2960236/e15bebe2-9497-48d9-8f08-ccf55618306c)

**Comment by jojo12** [comment]
ist behoben, seit dem letzten mod_uddeim nicht mehr, kann geschlossen werden.

**Comment by jojo12** [comment]
dafür kommt es jetzt beim andern, das nur Kunena und kein CB hat
`Function | Location
-- | --
() | JROOT/libraries/src/Router/Router.php:155
Joomla\CMS\Router\Router->parse() | JROOT/libraries/src/Application/SiteApplication.php:754
Joomla\CMS\Application\SiteApplication->route() | JROOT/libraries/src/Application/SiteApplication.php:244
Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
require_once() | JROOT/index.php
`

**Comment by joomod** [comment]
hmm,
kann es sein, dass du seit heute morgen einiges auf der Seite geändert hast?
(zB schein Joomla SEF nicht mehr aktiv zu sein)
die  404 links im Notifier hatten immer community/features
https://www.folk-tanz.ch/community/features/index.php?option=com_uddeim&task=ajaxGetNewMessages
aber das taucht jetzt bei keinem menulink mehr auf ???

zum neuen Fehler bräuchte ich noch etwas mehr Info.
in dem call stack ist ja gar nix von uddeim ?

**Comment by jojo12** [comment]
ja, sorry, heute nachmittag musste ich umstellen, um einen Link herauszufinden. Wollte eigentlich wieder zurücksetzen, aber dann kam ein Anruf. Jetzt ist wieder SEF

als ich error debug angestellt hatte, erschien das genau an der Stelle des Modules!

**Comment by joomod** [comment]
war da keine Überschrift / Fehlerbezeichnung dabei?

**Comment by jojo12** [comment]
nur "Oops"

**Comment by joomod** [comment]
ja, jetzt mit aktiviertem SEF ist der alte Fehler wieder da (dafür der große nicht mehr :))
- ganz ehrlich: ich denke, dass da irgendwo in deinen Menu(links) und aliases ein Fehler steckt.
vorhin (ohne SEF) hat man ja gesehem, dass der code die item_id (irgendwas mit 9xxx) für uddeim korrekt ausliest.

**Comment by jojo12** [comment]
![cass Stack](https://github.com/slabbi/uddeIM/assets/2960236/448dc3e3-630f-4721-84e0-aa7dec8e3b5a)

**Comment by jojo12** [comment]
ich schau mir das dann mit menü und aliases mal an.
lassen wir das hier. (ich brauchs dies ja eigentlich nicht, no messages=yes

**Comment by joomod** [comment]
im Prinzip geht es bei beiden Fehlern darum, dass der Link der an Ajax übergeben wird nicht stimmt.
mit SEF  war  es (je nach Seite mit features oder ohne)
https://www.folk-tanz.ch/community/features/index.php?option=com_uddeim&task=ajaxGetNewMessages&no_html=1&format=raw
ohne SEF ist es halt das typische index.php?option= .....  &itemid=9811

ich hab mal auf der Seite alles durchgeklickt:
der Fehler tritt nur bei dem Menupunkt Community auf,
da steht immer https://www.folk-tanz.ch/community/ am Anfang und schon der direkte
Aufruf https://www.folk-tanz.ch/community/features/index.php ergibt auch eine 404
(das könnte die Ursache sein) ???

vergleiche mal in der Konsole (webmaster Werkzeug) des Browser was er als
GET (not found) für einen link angibt  (einmal mit SEF, und z.Vergleich ohne SWF)

**Comment by joomod** [comment]
die richtigen Links habe ich gefunden (muß mal schauen wieso die anders geeriert werden)
https://www.folk-tanz.ch/community/features/?option=com_uddeim&task=ajaxGetNewMessages&no_html=1&format=raw
https://www.folk-tanz.ch/community/?option=com_uddeim&task=ajaxGetNewMessages&no_html=1&format=raw
also o h n e das index.php (dann kommt eine weiße Seite nur mit **0**)

**Comment by joomod** [comment]
probiers mal damit
[mod_uddeim.zip](https://github.com/slabbi/uddeIM/files/14515692/mod_uddeim.zip)

**Comment by jojo12** [comment]
Hab dies auch in PM geschrieben:

Guten Morgen,
mit dem letzten mod_uddeIM.php kommt keine Fehlermeldung mehr
hier mit CB und Kunena nicht und auch bei der Seite ohne CB mit Kunena nicht.

Ich schicke dies mit starker Verschlüsselung. Hier ist es so, wenn ich kein Passwort eingebe, dann kommt keine Fehlermeldung. Die kommt nur, wenn ich Passwort wähle und etwas einsetze.

Jojo

**Comment by jojo12** [comment]
kann man glaub ich schliessen.
