### ISSUE TITLE
deprecated info, when using uddeim 5 for Joomla 5 RC1 with latest CB

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#35]
when opening a profile (my admin) I get:
Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in mysite.ch/components/com_comprofiler/plugin/user/plug_privatemessagingsystem(uddeimpms)/pms.uddeim.php on line 468

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in mysite.ch/components/com_comprofiler/plugin/user/plug_privatemessagingsystem(uddeimpms)/pms.uddeim.php on line 472

**Comment by joomod** [comment]
aggr, damn new php rules :(  will correct this soon online and a next upload
you may correct this by adding **?? ''**  to stripslahes($var ?? '') in the above lines.

**Comment by jojo12** [comment]
no problem, I (and for sure not only me) am very happy about your work. So I will help with testing!
