### ISSUE TITLE
after update chat.png is not uploaded where it should be, so I get alternate text instead of img

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#37]
after update chat.png is not uploaded where it should be, so I get alternate text instead of img.
I had to upload it in the module folder manually.

**Comment by joomod** [comment]
you are right - chat.png is missing in the setup xml

I updated the uddeim_mailbox.php to use the template icon menu_postbox.png,
so the extra chat.png is no longer needed

**Comment by jojo12** [comment]
Sorry, when I reopen this: I think, you should adapt tne link in the php.
