### ISSUE TITLE
would be helpful to activate the issue labels (on the sidebar right here)

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#38]
@joomod @slabbi 
I think, it would really be helpful to activate the issue labels (on the sidebar right here), so it's easier to declare what the issue is
(is it a bug, is it deprecated....)
who has the rights to activate this? I think @slabbi

I will help with testing, I am testing in other projects too!
Jojo

**Comment by slabbi** [comment]
Everybody with write access can edit/modify labels.

**Comment by jojo12** [comment]
Please can you give me write access!

**Comment by slabbi** [comment]
granted
