### ISSUE TITLE
white page with Undefined constant "_UDDEIM_MESSAGEINFO_SENT"

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#39]
Hallo, ich habe eine Webseite upgedatet von 4.4.2 auf 5.0.3. php 8.1. Darauf war ein uddeIM, das nicht mehr funktionierte. Ich hab uddeIM 5 RC1 drüber installiert. Nun konnte ich wieder IMs posten mit Email und Nachricht . Es kommt an, allerdings kommt eine weisse Seite mit
`Undefined constant "_UDDEIM_MESSAGEINFO_SENT"`

**Comment by jojo12** [comment]
yes, with that, the white page is away, thanks.
[Ich bin mir nicht sicher: wenn du eine Lösung zum Testen vorschlägst, ob du die gleich schon ins definitive änderst.
Ich gehe dann davon aus, dass Du es erst fremdtesten lässt. Bei erfolgreichem Testen setze ich "known solution".
Vielleicht wäre es dann gut, mit dem fixen des Fehlers, das "known solution" durch "fixed" zu ersetzen oder zumindest zu entfernen, bevor wir das Problem schliessen.]

**Comment by joomod** [comment]
dieser Fhehler war ja kein echter Fehler, sondern ein update Vergessen meinerseits.
hatte es blos beim Zusammenstellen der ZIP übersehen (die germanf.php ist ja ok)
