### ISSUE TITLE
Class "JArrayHelper" not found

### ISSUE THREAD

**Issue by pmlejnek** [slabbi/uddeIM#4]
Hi,
I used to use this component on previously installations of Joomla 3.x, and I want to continue using it on Joomla 4.
After installing the com_uddeim_j40 (I previously uninstall the old version when upgrading to Joomla 4 from Joomla 3) I'm getting the following error after a successful installation:

<h1 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 400; line-height: 1.2; color: var(--template-bg-dark); font-size: 1.65rem; font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An error has occurred.</h1><blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="badge bg-secondary" style="box-sizing: border-box; display: inline-block; padding: 0.3rem 0.2rem; font-size: 0.75rem; font-weight: 700; line-height: 1; color: rgb(255, 255, 255); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.2rem; --bg-opacity: 1; background-color: rgba(var(--secondary-rgb), var(--bg-opacity))  !important; margin-bottom: 0px;">0</span><span> </span>Class "JArrayHelper" not found</blockquote><div style="box-sizing: border-box; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Call stack
--
# | Function | Location
1 | () | JROOT/components/com_uddeim/uddeimlib38.php:104
2 | uddeIMmosGetParam() | JROOT/administrator/components/com_uddeim/admin.uddeim.php:63
3 | require_once() | JROOT/administrator/components/com_uddeim/uddeim.php:17
4 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
5 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
6 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:355
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:294
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:61
11 | require_once() | JROOT/administrator/index.php:32

</div>

I'm using Joomla 4.2.6, PHP 8.2.1, MySQL 8.0.31

I previously removed the component, but the database tables are still there from the version uddeIM 3.8.

What am I missing and how to correct it?

**Comment by slabbi** [comment]
I do not longer support uddeIM, I am sorry. Joomla regularly breaks backwards compatibility, so I don't do it anymore.
https://www.joomlapolis.com/forum/25-uddeim-plugin-and-component/238073-support-continues-for-joomla-3-x-branch-only

According to
https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

"The following classes and interfaces have been removed in Joomla! 4.0:
    JArrayHelper
use Joomla\Utilities\ArrayHelper; instead. "

Please feel free to fix the code and create a pull request.

**Comment by slabbi** [comment]
There was a pull request today. Can you check if this also fixes this issue?
