### ISSUE TITLE
installing RC2 gives deprecated

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#40]
Joomla 5.0.3 php 8.2.16

Deprecated: Creation of dynamic property com_uddeimInstallerScript::$release is deprecated in /home/folktanz/public_html/tmp/install_65e5c194bcb0d/script50.php on line 31

Deprecated: Creation of dynamic property com_uddeimInstallerScript::$minimum_joomla_release is deprecated in /home/folktanz/public_html/tmp/install_65e5c194bcb0d/script50.php on line 33

**Comment by joomod** [comment]
tried to fix it - RC2 has been updated
