### ISSUE TITLE
white page when using "starke Verschlüsselung" and entering password

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#42]
When I have the admin setting "Starke Verschlüsselung" and use the Passwort in the window, I get a white page
`Call to undefined function mcrypt_module_open()`
with other settings, I can't enter a password, and then there is no problem
[it's the first time I tried the "Passwort", so I don't know if it worked ever before]

**Comment by jojo12** [comment]
Interessant: wenn ich Verschlüsselung "Starke Veschlüsselung" abschalte, (ich habe nun base64 gewählt), dann kommt das Problem "Seite nicht gefunden" nicht mehr!

**Comment by joomod** [comment]
ok, ich muß ehrlich gestehen, ich hab die ganzen encrypt Teil immer übersprungen :(

**Comment by joomod** [comment]
1. Ergebniss
starke Verschlüsselung benutzt mcrypt Funktionen, die aber in php7.2 entfernt wurden => Fehler
 ich muß also schauen ob ich das in openssl umschreiben kann
bis dahin kann ich starke Verschlüsselung nur deaktivieren.

vermutlich kommt davon ja auch der Ajax Fehler

**Comment by joomod** [comment]
hab die crypt_class mal auf open_ssl umgeschrieben
[crypt.class.zip](https://github.com/slabbi/uddeIM/files/14498601/crypt.class.zip)

versuch mal ob das funktioniert

**Comment by jojo12** [comment]
test gobt
`openssl_random_pseudo_bytes(): Argument #1 ($length) must be greater than 0`

**Comment by joomod** [comment]
probiers mal damit
($length müßte eigentlich 16 sein)
[crypt.class.zip](https://github.com/slabbi/uddeIM/files/14499532/crypt.class.zip)

**Comment by joomod** [comment]
im Prinzip ist crypt_mode 4 sowieso nur eine halbe Sache.
bei vielen Funktionen (zB in pms_) wird es auf crypt_mode  1 zurückgesetzt.
mode 3 läuft immer,  mode 2 ist durch das Passwort (wie bei mode 4) verstärkt

**Comment by joomod** [comment]
was geht bei starke Verschlüsselung aktuell nicht (Fehler?)

**Comment by jojo12** [comment]
übliche white page mit obiger Fehlermeldung
'openssl_random_pseudo_bytes(): Argument #1 ($length) must be greater than 0'

vorher
![Anmeldungsversuch](https://github.com/slabbi/uddeIM/assets/2960236/ddddeeb7-884d-4fe9-8d2a-dd529e85f0cc)

**Comment by joomod** [comment]
ja, die Passwortabfrage kommt auch bei mode 2. (1 und 3 ist ohne)

das mit dem Length 0 kann ich überhaupt nicht nachvollziehen,
schließlich habe ich mit $ivSize = openssl_cipher_iv_length($method) ?? 16;
die Länge auf 16 gesetzt (falls 0) - zumindest wenn du die 2.Version hochgeladen hast

**Comment by jojo12** [comment]
![white](https://github.com/slabbi/uddeIM/assets/2960236/3d1a5a67-31fd-4010-82ab-aa507342ba95)

**Comment by joomod** [comment]
hast Du die 2. version von crypt.class hochgeladen ?

**Comment by joomod** [comment]
habe leider festgestellt, dass ich den falschen operator in der 2. version eingesetzt habe
(statt ?? 16 muß es ?: 16 sein) aber da stecken noch mehr Fehler drin.
diese Version 
[crypt.class_v3.zip](https://github.com/slabbi/uddeIM/files/14537273/crypt.class_v3.zip)
läuft zwar (bei mir), aber das Entschlüsseln funktioniert noch nicht.

**Comment by jojo12** [comment]
with that I get:
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/4b505db8-bb08-44eb-b4f1-cae73c3822e1)

**Comment by jojo12** [comment]
Simmt ich kann strarke Verschlüsselung abschicken, aber nicht öffnen

**Comment by jojo12** [comment]
ich teste mit starker Verschlüsselung. Ich kann ein Passwort eingeben (muss aber anscheinend nicht).
In der Email ist der Text lesbar, allerdings kein ü ( wohl kein utf-8)
Im Postfach kann ich Nachricht anklicken, dann zeigt sich "verschlüsselt - Passwort erforderlich".
Ich habe erst nach einiger Zeit rausgefunden, dass man dann diesen Text anklicken muss. Erst dann öffnet sich ein Fenster für die Passworteingabe. (Vielleicht würde ein anderer Text helfen, z.B. "Verschlüsselt - Passwort hier eingeben".
Es ist auch so bei mir, dass beim ersten Mal anklicken nichts passiert, das Entschlüsselungsfenster kommt erst beim zweiten Anklicken. (Sollte wohl nicht so sein).
Wenn ich dann ein falsches Passwort eingebe kommt "Falsches Passwort". Muss so sein.
Wenn ich das richtige Passwort eingebe, kommt das Fenster in dem die Nachricht sein sollte, aber es ist leer, ausser dem Strich, unter dem man antworten kann.

**Comment by joomod** [comment]
ich bin momentan am überarbeiten und hab das Verschlüsselungsthema
zurückgestellt.
Im Augenblick schreibe ich den Autocompleter neu, da der alte ja auf 
uralt Mootools u.a. aufbaut und deshalb ausgemustert werden sollte.
sobald ich das hab ist die Openssl Verschlüsselung wieder dran

**Comment by jojo12** [comment]
alles klar, ich will dich nicht an etwas festbinden, auch nicht drängen, es gibt ja auch noch das reale Leben.
Ich hoffe auch nicht, dass es dir verleidet ist. Ich bin schon mit dem was ist, äusserst zufrieden (ich bin mir sicher, auch andere. Melde dann halt auch Nebensächlichkeiten, damit es nicht deswegen verworfen wird.

**Comment by joomod** [comment]
kein Problem,
die ganze Sache mit Mootols etc. ist mir halt immer wieder aufgestoßen,
hat halt noch keiner gemeckert, dass der Autocompleter nicht funktioniert,
deshalb hab ich da mal aufgeräumt.
Ich denke die Openssl Verschlüsselung ist für die meisten eh übertrieben :)
aber kommt als nächstes (in 14 Tagen bin ich wieder zurück)
dann gibt es auch sowas wie die Version 5.1

**Comment by joomod** [comment]
so, die openssl Verschlüsselung sollte jetzt funktionieren (hoff ich :)
bitte mal die **v5.1.** ausprobieren.

**Comment by jojo12** [comment]
5.1 RC1 openssl Verschlüsselung funktioniert gut! Danke ( Frohe Ostern)
