### ISSUE TITLE
uddeIM Notifier on a site without CB

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#43]
I installed uddeIM 5 RC2 on a site without CB and activated uddeIM Notifier.
I get a read page. With the debug I get:
`Error: Cannot redeclare uddeIMmodCheckCB() (previously declared in /home/jem/domains/helix.joomlaeventmanager.net/public_html/modules/mod_uddeim/mod_uddeim.php:376)`
and
`
    }
}
function uddeIMmodCheckCB() {
    $udd_pathtocb = uddeIMgetPath('absolute_path')."/components/com_comprofiler/comprofiler.php";
    if (file_exists($udd_pathtocb))
        return true;
    return false;
}
 `

**Comment by joomod** [comment]
da die Funktion wirklich nur in mod_uddeim existiert und dort aufgerufen wird,
kann nur bedeuten, dass du das Modul irgendwie/wo ein zweites Mal zu laden versuchst?
generell wäre es möglich den Fehler mit einer exists Abfrage abzufangen:
```
if (!function_exists('uddeIMmodCheckCB')) {
function uddeIMmodCheckCB() {
...
} }
```

**Comment by joomod** [comment]
was hast Du im Modul setup bei **Displayed name** eingestellt?
(vielleicht noch Firstname (CB only) ?)
weil nur dann geht der code überhaupt in die CB Abfrage

**Comment by jojo12** [comment]
Nein, es war bei username!
Aber das ganze ist nicht mehr erschienen, vielleicht, weil ich es jetzt auf Kunena 6 eingestellt habe.
kann, glaub ich geschlossen werden.

**Comment by joomod** [comment]
seltsam, eigentlich ruft der code die uddeIMmodCheckCB Funktion nur auf wenn case 2 (Firstname) gewählt ist.
egal, ich hab die Abfrage jetzt direkt eingebunden

das ist das resultat von wingrep (durchsucht **alle** Dateien:  hier nach uddeIMmodCheckCB)
mod_uddeim.php
00108: case 2 : if (uddeIMmodCheckCB()) {
00379: function uddeIMmodCheckCB() {
