### ISSUE TITLE
White page, wenn Kunena eingestellt

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#44]
zum nachmachen:
Backend: die uddeIM-Settings in Integrierung sind Kunena 6.0
Frontend: ich gehe in die Einstellungen des Mailbox Moduls und wähle Einstellungen:
Ich finde dort im Menü -> Forum und wähle das:
es kommt eine weisse Seite mit "Oops! Ein Fehler trat beim Update der Datenbank auf."
mit debug: call stack

`1 | () | JROOT/libraries/src/Router/Router.php:155
-- | -- | --
2 | Joomla\CMS\Router\Router->parse() | JROOT/libraries/src/Application/SiteApplication.php:754
3 | Joomla\CMS\Application\SiteApplication->route() | JROOT/libraries/src/Application/SiteApplication.php:244
4 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
5 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
6 | require_once() | JROOT/index.php:32`

**Comment by jojo12** [comment]
![EinstellungenForum](https://github.com/slabbi/uddeIM/assets/2960236/88d4b6f4-08be-49a6-97d9-fb9b40c5f236)

**Comment by joomod** [comment]
sorry, mit der Menueinbindung meinte ich das Hauptmenu der Seite, also wo dann der Link Forum erscheint. (das könnte man direkt, also aus den Kunenaeinträgen - sollte man aber nicht oder eben über ein Alias, der dann auf die Kunenaeinträge zugreift machen)
empfohlen wird Alias, da sonst (wie vielleicht hier) Durcheinander entstehen können.

**Comment by joomod** [comment]
ich versuch mal ob sich das mit Route oder SEF lösen lässt

**Comment by joomod** [comment]
P.S. das mit den Alias Einträgen gilt übrigens auch für CB

**Comment by joomod** [comment]
was hast du denn geändert, jetzt funktioniert ja der link
(ich habe gesehen, dass du den Notifier deaktiviert hast)

**Comment by jojo12** [comment]
Was ich gemacht habe (habs ansheinend woanders gemeldet, zuerst sef abgestellt, kunena menu auf wiederherstellen, dann SEF eongestellt.

**Comment by joomod** [comment]
jedefalls schein mein link im script richtig zu sein :)
ist manchmal schon ganz schön tricky mit den menus und sef und alias
momentan passt es also
