### ISSUE TITLE
strange: updating simple notifier module gives error, new install not

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#46]
0 Call to undefined method Joomla\CMS\Installer\Adapter\ModuleAdapter::get() 

1 | () | JROOT/tmp/install_66092ea0baacf/script.php:51
-- | -- | --
2 | mod_uddeim_simple_notifierInstallerScript->update() | JROOT/libraries/src/Installer/LegacyInstallerScript.php:158
3 | Joomla\CMS\Installer\LegacyInstallerScript->__call() | JROOT/libraries/src/Installer/LegacyInstallerScript.php:187
4 | Joomla\CMS\Installer\LegacyInstallerScript->callOnScript() | JROOT/libraries/src/Installer/LegacyInstallerScript.php:69
5 | Joomla\CMS\Installer\LegacyInstallerScript->update() | JROOT/libraries/src/Installer/InstallerAdapter.php:1080
6 | Joomla\CMS\Installer\InstallerAdapter->triggerManifestScript() | JROOT/libraries/src/Installer/InstallerAdapter.php:777
7 | Joomla\CMS\Installer\InstallerAdapter->install() | JROOT/libraries/src/Installer/Installer.php:652
8 | Joomla\CMS\Installer\Installer->install() | JROOT/administrator/components/com_installer/src/Model/InstallModel.php:214
9 | Joomla\Component\Installer\Administrator\Model\InstallModel->install() | JROOT/administrator/components/com_installer/src/Controller/InstallController.php:52
10 | Joomla\Component\Installer\Administrator\Controller\InstallController->install() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
12 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
13 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
14 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
15 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
16 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
17 | require_once() | JROOT/administrator/index.php:32

**Comment by joomod** [comment]
is this from v 5.1. ?

**Comment by joomod** [comment]
ok, I see in update there is a call to $parent->get('manifest')->version
which gives the error.  (this is not called on new install).
I must check it.

**Comment by jojo12** [comment]
yes the new strong decryption is fine, so I closed the issue! Thanks.

**Comment by joomod** [comment]
please try replacing in the notifier script:
$parent->get('manifest')->version  to **$parent->getManifest()->version**

**Comment by joomod** [comment]
> yes the new strong decryption is fine, so I closed the issue! Thanks.
fine, the **openssl** was a bit tricky to understand.

also try the new autocompleter.
I have edit the (not light) JS, so it is (as far as I have found) the first which
handels multiple input (after the seperator is entered to the input field) :)

**Comment by jojo12** [comment]
the simple notification module installation works with this change.
But I had not the old version installed, so I don't can test it to update!

**Comment by joomod** [comment]
so let's hope :)
the change is what I found on J2.5 -> J4

**Comment by jojo12** [comment]
I restored my backupped site with uddeim 5.0 RC2 and reinstalled 5.1 over this. Works fine no error.
(I don't know what was the problem before :-( )
