### ISSUE TITLE
Alert: white page with error in udeeIM5.1RC

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#48]
während Wechsel in Verschlüsselungen: nix geht mehr.
Oops!
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'u.id NOT IN (62) ORDER BY u.name' at line 3

**Comment by joomod** [comment]
hmm,
was meinst du mit "während Wechsel"  -  im backend?

**Comment by jojo12** [comment]
alles lief gut solange ich in open ssl verschlüsselung war.
Weil es auf einer anderen Seite eine sub von joomlaeventmanager.net Probleme gab, wollte ich es bei mir testen und wechselte auf eine andere Verschlüsselung, dann alle andern, dann zurück auf open ssl, aber immer dieselbe fehlermeldung. siehe oben.
mit debug kam keine call stack.

**Comment by joomod** [comment]
ist der fehler jetzt im backend - beim Wechsel?
oder danach beim Nachrichten versenden?

**Comment by jojo12** [comment]
Ich bin danach jeweils auf compose gegangen, dann kam fehlef

**Comment by joomod** [comment]
also schon beim aufruf der compose seite - nicht erst beim senden

**Comment by jojo12** [comment]
Ja

**Comment by joomod** [comment]
und was passiert wenn du keine  verschlüsselung wählst?
(bei mir läuft alles ohne fehler - ich habe aber Mysql)

**Comment by jojo12** [comment]
ich habe mysqli.
Ich habe backup restored mit uddeim 5.0 RC2 und 5.1 RC drüber installiert!
Funktioniert wieder. Weiss nicht weshalb vorher ein Problem!

**Comment by joomod** [comment]
komisch, ober in der Fehlermeldung steht aber
_your **MariaDB** server_

**Comment by jojo12** [comment]
Komisch, auch auf der andern Webseite funktioniert es wieder

**Comment by jojo12** [comment]
Kann geschlossen werden
