### ISSUE TITLE
only for information: someone tries to earn money

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#49]
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/db15c502-3912-4908-a6df-26389cc96509)

**Comment by joomod** [comment]
wo du so überall rumsurfst :)
das ist aber ok, ich habe es dort angeboten um im Tausch die älteren uddeim templates von 9themestore zu bekommen (bin gerade dabei diese zu integrieren, sind ja no J3)

**Comment by jojo12** [comment]
:-) na dann ist ja gut.
