### ISSUE TITLE
uddeim5.2RC1b: seems you forgot something again!

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#50]
trying to update via install the module mod_uddeim_simple_notifier50.zip I get:
0 Call to undefined method Joomla\CMS\Installer\Adapter\ModuleAdapter::get()

**Comment by joomod** [comment]
hmm, can you give me the call stack?
the update script includes the new $parent->getManifest()->version
not the old $parent->**get**('manifest')->version
may be because I have not updated the manifest file to v5.1 or 5.2 so your system uses the
the old file???
try replace the xml file
[mod_uddeim_simple_notifier.xml.zip](https://github.com/slabbi/uddeIM/files/14893118/mod_uddeim_simple_notifier.xml.zip)

**Comment by jojo12** [comment]
1 | () | JROOT/tmp/install_66111aeb35d92/script.php:51
-- | -- | --
2 | mod_uddeim_simple_notifierInstallerScript->update() | JROOT/libraries/src/Installer/LegacyInstallerScript.php:158
3 | Joomla\CMS\Installer\LegacyInstallerScript->__call() | JROOT/libraries/src/Installer/LegacyInstallerScript.php:187
4 | Joomla\CMS\Installer\LegacyInstallerScript->callOnScript() | JROOT/libraries/src/Installer/LegacyInstallerScript.php:69
5 | Joomla\CMS\Installer\LegacyInstallerScript->update() | JROOT/libraries/src/Installer/InstallerAdapter.php:1080
6 | Joomla\CMS\Installer\InstallerAdapter->triggerManifestScript() | JROOT/libraries/src/Installer/InstallerAdapter.php:777
7 | Joomla\CMS\Installer\InstallerAdapter->install() | JROOT/libraries/src/Installer/Installer.php:652
8 | Joomla\CMS\Installer\Installer->install() | JROOT/administrator/components/com_installer/src/Model/InstallModel.php:214
9 | Joomla\Component\Installer\Administrator\Model\InstallModel->install() | JROOT/administrator/components/com_installer/src/Controller/InstallController.php:52
10 | Joomla\Component\Installer\Administrator\Controller\InstallController->install() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
12 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
13 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
14 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
15 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
16 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
17 | require_once() | JROOT/administrator/index.php:32
did not try the new file, will do that now

**Comment by jojo12** [comment]
yes, with this xml, there is no error message!

**Comment by joomod** [comment]
ok, I will update the package now

**Comment by jojo12** [comment]
RC1b again

**Comment by joomod** [comment]
ok, corrected the simple notifier to v5.2,
but it should run (or may be not if no updated is detected),
but not such an error.
