### ISSUE TITLE
Updating Deletes Settings

### ISSUE THREAD

**Issue by mrkalchemy** [slabbi/uddeIM#52]
If you upgrade the uddeIM component the existing config.class.php file will be overwritten by the one bundled in the zip package. This has the effect of wiping any custom configuration and resetting all settings to their defaults.

One solution could be to rename the default config.class.php file to config.class.dist.php and use that in the install script.

**Comment by mrkalchemy** [comment]
I just submitted a pull request (https://github.com/slabbi/uddeIM/pull/53) with my proposed solution.

Thanks.

**Comment by slabbi** [comment]
A config.class.php should not be included in the zip.
uddeIM creates a default file when it is started the first time.

**Comment by mrkalchemy** [comment]
For future visitors :  There is a backup/restore settings option in Maintenance tab of the backend. You need to use this before upgrading the extension.
