### ISSUE TITLE
J!5.1 php 8.2.16 and uddeIm5.2RC1b deprecated

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#54]
Deprecated: preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in mysite.ch/components/com_uddeim/bbparser.php on line 216

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in mysite.ch/components/com_uddeim/postbox.php on line 671

Deprecated: stripslashes(): Passing null to parameter #1 ($string) of type string is deprecated in mysite.ch/components/com_uddeim/postbox.php on line 747

**Comment by joomod** [comment]
thank you,
corrected for the next update
