### ISSUE TITLE
_uddeIM5_for_Joomla5_UNSUPPORTED Issue

### ISSUE THREAD

**Issue by 60600009** [slabbi/uddeIM#55]
Hi

uddeIM installed OK, Ihad no issues with configuring the component, I can access it from the frontend and everything is OK until I go to compose a message and I get the following:

The requested page can't be found.
An error has occurred while processing your request.
You may not be able to visit this page because of:
•	an out-of-date bookmark/favourite
•	a mistyped address
•	a search engine that has an out-of-date listing for this site
•	you have no access to this page
Go to the Home Page
If difficulties persist, please contact the website administrator and report the error below.
500 behavior::framework not found. 

I have used uddeIM for years and am glad that it is being continued.

Thanks
Stuart

Joomla 5.1.0
PHP 8.2.2
MySQLi     10.6.5-MariaDB 
Apache 2.4.51

More information is attached
[Joomla - uddeIM issues.docx](https://github.com/slabbi/uddeIM/files/15050674/Joomla.-.uddeIM.issues.docx)

#

**Comment by jojo12** [comment]
Do you have really php 5.22? This is not possible!

**Comment by 60600009** [comment]
Your right, I don't have 5.2.2. 
Sorry, I made an error, I have 8.2.2.

**Comment by jojo12** [comment]
Can you say please, which from which uddeIm package do you write. The newest package right now is uddeIM 5.2 RC1b for J!5

**Comment by 60600009** [comment]
I downloaded the file from here, https://github.com/slabbi/uddeIM and separated the Joomla 5 package and installed it. 
Now that you have pointed it out I see there is a newer version here https://github.com/slabbi/uddeIM/releases/tag/v5.2-RC1 that is the version you are referring to. I will upgrade to the newer version and see if that makes a difference.

**Comment by 60600009** [comment]
Hi
I downloaded and installed uddeIM 5.2 RC1b, it installed properly without incident and as far as I can see (without using it for a while) it seems to work perfectly.
I have a request if possible, we are in Australia and the date format is Day Month Year which does not seem to be available in uddeIM, would it be possible to include thus date format in a future version.
Thanks for your help
Stuart Hunter

**Comment by joomod** [comment]
fine that v5.2 is working :)
there are many dateformats for  d-m-y, but you are right no digits only format (just 3 letter month)
I will add some in the next update

**Comment by joomod** [comment]
you may use (reeplace) this new admin.uddeim.php (added some shortdate formats)
[admin.uddeim.zip](https://github.com/slabbi/uddeIM/files/15062738/admin.uddeim.zip)
