### ISSUE TITLE
uddeIM5.3 works fine - thanks a lot

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#57]
Do you will put it in the JED? with slabbi

**Comment by slabbi** [comment]
I would like to help, but I can no longer log in on JED. A "secret key" is required, which I don't have.
Resetting the password doesn't work either, I just don't receive an email. 
I already know why I turned my back on Joomla.

**Comment by slabbi** [comment]
Yes, my JED account works again

**Comment by slabbi** [comment]
Have you committed all changes?
I don't see these.

**Comment by slabbi** [comment]
Cannot upload the zip you have created to JED since it has not a proper structure:

It should look like this:
![grafik](https://github.com/slabbi/uddeIM/assets/65805263/271d99d8-6a97-412c-b47e-8ebc87c1364c)

The zip files can be installed and contain a proper install script.
You should also push your changes to the repository.

**Comment by jojo12** [comment]
I only tried to write a review. This is, what I can. I didn't upload something. I?ve not the rights. The link is to your site and there is no uddeIM 5.3. You should change this!
Greetings 
Jojo

**Comment by jojo12** [comment]
@slabbi: to whoom are you writing?

**Comment by slabbi** [comment]
To @joomod :)

**Comment by joomod** [comment]
@slabbi 
sorry, I have not commited the changes of my releases, as I couldn't find out how to publish 
a release package in the main structure folder, where I can pick single files (I told, I'm new to github :)

I think the folder structure is not the main problem for JED.
I just run a test with JED checker and got a big list of errors and warnings
(ok, many, many come from the 3rd party addons, which I have not checked for J5)

I will go and try to fix the errors in the main component and modules/plugins first,
then we can talk about the xml errors (e.g. update server, name etc.)

it would be great if I could have helped to release an official component
(starting from updating it just for my own purpose)

![jed](https://github.com/slabbi/uddeIM/assets/149375504/1743b416-be34-48c8-8c11-017ea9ff56e5)

**Comment by slabbi** [comment]
Commit to "_uddeIM5_for_Joomla5_UNSUPPORTED"
I will rename this folder finally, so that it contains the J5 code.
The files outside that folder should be untouched because these are J1-J4 compatible.

**Comment by joomod** [comment]
I have finished v5.3.5  which completes the JED check without errors
(includes update ReCaptcha lib to actual version 1.3)
also I added an update server here on github and created a uddeim_update.xml
the 3rd party folder is deleted, because most won't run on J5 or I couldn't handle the errors

[uddeIM_5.3.5-j5.zip](https://github.com/slabbi/uddeIM/files/15275275/uddeIM_5.3.5-j5.zip)
[uddeim_update.zip](https://github.com/slabbi/uddeIM/files/15275278/uddeim_update.zip)

check it out

**Comment by slabbi** [comment]
Can you check this file, plz?
[uddeIM_5.3_j50_unzip1st.zip](https://github.com/slabbi/uddeIM/files/15276097/uddeIM_5.3_j50_unzip1st.zip)
The scripts to build this archive are in TOOLS. You need 7-zip only.

**Comment by joomod** [comment]
looks good, only the **admin.includes.php** (I have edit the uploaded file)
should be replaced by this  (new string in the createCFGstring)
`$cf.="defined('_JEXEC') or die( 'Direct Access to this location is not allowed.' );\n";`
so the config.class stay correct for the JEXEC check

[admin.includes.zip](https://github.com/slabbi/uddeIM/files/15276248/admin.includes.zip)

**Comment by joomod** [comment]
just the main changes for v5.0 (to be added in changelog.txt)

- completly updated code to run on Joomla 5 (without compat) and php 8.2
- new config.class v2.8 (added autocompleter and db save option)
- add config.class backup on update and option to always save to db
- completely renewed the autocompleter with new simple scripts (mootools and MIO removed)
- php mail function added a debug error function (if neccesary)
- removed 3rd party addon (SEF) as from J3 and no longer compatible
- added 5 new templates 
- updated ReCaptcha php to newest version 1.3 (php 8)
- premium addon integrated
- some minor style updates in the backend

I think this are the big points :)

**Comment by slabbi** [comment]
updated

You should use

**Comment by slabbi** [comment]
You should use
https://gitforwindows.org/
From the command line pull the complete repository "git pull". Then you can do changes and push these back using the GUI (scan, stage, commit, push).

**Comment by joomod** [comment]
thanks I will try
