### ISSUE TITLE
error in uddeim_searchbot.php

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#58]
When I am testing without compat plugin:
0 Call to undefined method Joomla\Database\Mysqli\MysqliDriver::getEscaped() 
Call Stack
1 | () | JROOT/plugins/search/uddeim_searchbot/uddeim_searchbot.php:163
-- | -- | --
2 | botSearchUddeIM() | JROOT/plugins/search/uddeim_searchbot/uddeim_searchbot.php:127
3 | plgSearchUddeIMmain() | JROOT/plugins/search/uddeim_searchbot/uddeim_searchbot.php:60
4 | plgSearchUddeIM16() | JROOT/plugins/search/uddeim_searchbot/uddeim_searchbot.php:21
5 | plgSearchUddeim_searchbot->onContentSearch() | JROOT/libraries/src/Plugin/CMSPlugin.php:289
6 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:454
7 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:111
8 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/components/com_search/models/search.php:146
9 | SearchModelSearch->getData() | JROOT/libraries/src/MVC/View/AbstractView.php:159
10 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/components/com_search/views/search/view.html.php:131
11 | SearchViewSearch->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:697
12 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_search/controller.php:39
13 | SearchController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
14 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/components/com_search/search.php:16
15 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
16 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
17 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
18 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:218
19 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:261
20 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
21 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
22 | require_once() | JROOT/index.php:32

**Comment by joomod** [comment]
ok, I just will upload a new 5.3 package
(keep 5.3 as uddeim component is untouched)

**Comment by jojo12** [comment]
Ok can be closed
