### ISSUE TITLE
5.3 5 final installing cb-plugins I get error

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#59]
error message:
danger
Upload fehlgeschlagen
Plugin version (5.1) different from Community Builder version (2.9.1)
Keine Speicherung Install CB Plugin wegen: Installation error

**Comment by joomod** [comment]
sorry my fault
didn't realize that version number must be the cb version which this plugin is for.
changed/commited the four cb2 xml files

**Comment by jojo12** [comment]
persists!
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/80b04ea9-c8af-4190-b8d5-4e483c52cee3)

**Comment by slabbi** [comment]
@joomod Please create a new release not before some tests have been done. 
I suggest to delete the 5.4 release, check in all changes and create small archives for the plugins published in the reported issue. When these have been verified to be ok, then - and only then - create a new release.

**Comment by slabbi** [comment]
Don’t create a release when the code is not available in the main branch. A release creates a source file which would be different from the installation release otherwise.

**Comment by joomod** [comment]
sorry, you are right - I was absolutely shure I  got the error.
I think I have, but haven't realized you created the package from the open folders
(where no index.html was stored) but not the install zips (including index.html)
so we must add an index.html to each cb-plugin

**Comment by joomod** [comment]
this are the new cb2 zips

[cb2_plug_pms_uddeim_j50.zip](https://github.com/slabbi/uddeIM/files/15282133/cb2_plug_pms_uddeim_j50.zip)
[cb2_plug_pms_uddeim_inbox_j50.zip](https://github.com/slabbi/uddeIM/files/15282134/cb2_plug_pms_uddeim_inbox_j50.zip)
[cb2_plug_pms_uddeim_blocking_j50.zip](https://github.com/slabbi/uddeIM/files/15282135/cb2_plug_pms_uddeim_blocking_j50.zip)
[cb2_plug_pms_uddeim_profilelink_j50.zip](https://github.com/slabbi/uddeIM/files/15282137/cb2_plug_pms_uddeim_profilelink_j50.zip)

**Comment by jojo12** [comment]
I installed them one by one-->works fine.
(but after I get an other error (post separately

**Comment by slabbi** [comment]
updated main branch
