### ISSUE TITLE
5.3 5 error after updating , and login

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#60]
0 Call to undefined function uddeIMgetDatabase() 
Call Stack

# | Function | Location
-- | -- | --
1 | () | JROOT/components/com_uddeim/includes.db.php:681
2 | uddeIMgetInboxCount() | JROOT/components/com_comprofiler/plugin/user/plug_pms_mypmspro/library/UddeIM.php:456
3 | CB\Plugin\PMS\UddeIM::getPMSunreadCount() | JROOT/components/com_comprofiler/plugin/user/plug_pms_mypmspro/pms.mypmspro.php:180
4 | getmypmsproTab->getPMSunreadCount() | JROOT/libraries/CBLib/CB/Legacy/cbPluginHandler.php:880
5 | cbPluginHandler->call() | JROOT/libraries/CBLib/CB/Legacy/cbPMS.php:52
6 | cbPMS->_callPlugin() | JROOT/libraries/CBLib/CB/Legacy/cbPMS.php:84
7 | cbPMS->_callPluginTypeMethod() | JROOT/libraries/CBLib/CB/Legacy/cbPMS.php:144
8 | cbPMS->getPMSunreadCount() | JROOT/modules/mod_cblogin/mod_cblogin.php:183
9 | include() | JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:52
10 | Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/ModuleDispatcher.php:55
11 | Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch() | JROOT/libraries/src/Helper/ModuleHelper.php:291
12 | Joomla\CMS\Helper\ModuleHelper::renderRawModule() | JROOT/libraries/src/Helper/ModuleHelper.php:162
13 | Joomla\CMS\Helper\ModuleHelper::renderModule() | JROOT/components/com_comprofiler/comprofiler.html.php:953
14 | HTML_comprofiler::loginForm() | JROOT/components/com_comprofiler/comprofiler.php:1181
15 | login() | JROOT/components/com_comprofiler/comprofiler.php:147
16 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
17 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
18 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
19 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:218
20 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:261
21 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
22 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
23 | require_once() | JROOT/index.php:32

**Comment by joomod** [comment]
ah, yes
the cb UddeIM.php doesn't know and so couldn't call uddeimlib50.php
and as I deleted the formerly switch uddeimlib.php cb doesn't load any lib
where the uddeIMgetDatabase() is defined.
as we couldn't wait for cb to be updated I will write a uddeimlib.php
where the new uddeimlib50 is called, so cb can load it.

**Comment by joomod** [comment]
add this to your site/com_uddeim folder and try
[uddeimlib.zip](https://github.com/slabbi/uddeIM/files/15281534/uddeimlib.zip)

**Comment by slabbi** [comment]
upated the main

Please do NOT create a new release.
I have removed the release twice because it was inconsistent with the main branch.

Give me an ok when all packages have been checked in and the main branch is bug free.

**Comment by slabbi** [comment]
Forgot: Also do not create tags line uddeIM 5.4 because it is NOT the 5.4 release.

Tags like 5.3-20240511 or 5.3-20240512 are ok when you want to keep a repository state.
