### ISSUE TITLE
Error in CB: 0 Call to undefined method CBLib\Database\Driver\CmsDatabaseDriver::execute()

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#61]
0 Call to undefined method CBLib\Database\Driver\CmsDatabaseDriver::execute() 

1 | () | JROOT/components/com_comprofiler/plugin/user/plug_privatemessagingsystem(uddeimpms)/pms.uddeim.php:235
-- | -- | --
2 | getuddeimTab->_sendPMSuddeimMSG() | JROOT/components/com_comprofiler/plugin/user/plug_privatemessagingsystem(uddeimpms)/pms.uddeim.php:274
3 | getuddeimTab->sendUserPMS() | JROOT/components/com_comprofiler/plugin/user/plug_privatemessagingsystem(uddeimpms)/pms.uddeim.php:444
4 | getuddeimTab->getDisplayTab() | JROOT/libraries/CBLib/CB/Legacy/cbPluginHandler.php:880
5 | cbPluginHandler->call() | JROOT/libraries/CBLib/CB/Legacy/cbTabs.php:1611
6 | cbTabs->_callTabPlugin() | JROOT/libraries/CBLib/CB/Legacy/cbTabs.php:357
7 | cbTabs->generateViewTabsContent() | JROOT/libraries/CBLib/CB/Legacy/cbTabs.php:443
8 | cbTabs->getViewTabs() | JROOT/libraries/CBLib/CB/Legacy/CBuser.php:410
9 | CBuser->getProfileView() | JROOT/components/com_comprofiler/comprofiler.html.php:341
10 | HTML_comprofiler::userProfile() | JROOT/components/com_comprofiler/comprofiler.php:625
11 | userProfile() | JROOT/components/com_comprofiler/comprofiler.php:117
12 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
13 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
14 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
15 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:218
16 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:261
17 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
18 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:58
19 | require_once() | JROOT/index.php:32

**Comment by joomod** [comment]
found:  CB still uses old commands in their CB_database library (eg. getEscaped instead the new escape)
and so still uses **query()** instead the **new execute()** command
so try this (only 2, the others don't have execute)

[cb2_plug_pms_uddeim_j50.zip](https://github.com/slabbi/uddeIM/files/15282427/cb2_plug_pms_uddeim_j50.zip)
[cb2_plug_pms_uddeim_blocking_j50.zip](https://github.com/slabbi/uddeIM/files/15282428/cb2_plug_pms_uddeim_blocking_j50.zip)

**Comment by slabbi** [comment]
updated the main branch

**Comment by jojo12** [comment]
installed the 2 above and tested. Works fine.

**Comment by joomod** [comment]
thank you
