### ISSUE TITLE
No messages in Backend

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#62]
A friend asked me, why he can't see any messages in the backend. So I saw in the menue, that there should be this possibility, to send and receive PMS in the backend.
[@joomod: Ich hoffe, Du siehst mich nicht als Spielverderber! Das Ganze ist jetzt schon soo gut]

A second thing: font color there (in the admin tables is not visible: I tried in admin.uddeim.css with adding color: #000
to table.adminlist td

**Comment by joomod** [comment]
nein, das ist super - es soll ja funktionieren, und alle Optionen selbst zu testen ist sehr mühsam

**Comment by slabbi** [comment]
There is no function to create uddeIM messages in backend (only Jommla PMS messages).

**Comment by joomod** [comment]
hmm, bin mir nicht sicher was Du meinst?
Nachrichten im backend?
ich habe gerade bei meiner J3 installation geschaut, da sind auch keine Nachrichten im backend,
zumindest nicht solange keine freigegeben werden müssen (wenn moderiert auf JA gesetzt ist)
ich denke Du meinst den Menu button ganz oben (Nachrichten bearbeiten)?

das mit der Schrift schau ich gerade

**Comment by slabbi** [comment]
Genau diese meint er vermutlich.
Jommla hatte zu meiner Zeit eine primitive Nachrichtenfunktion, die aber nichts mit uddeIM Nachrichten zu tun hat.
Es macht mMn auch keinen Sinn eine solche Funktion ins Backend einzubauen. Wer sich dort einloggen kann, hat auch Zugriff auf das Frontend. "Nachrichten lesen" ist auch keine typische Backend-Funktion. Hier sollten Administrationsaufgaben erledigt werden.

**Comment by jojo12** [comment]
So müsste man das eigentlich verstecken?

**Comment by joomod** [comment]
vielleicht sollte ich die Buttobeschriftung einfach in "Nachrichten freigeben" ändern?
(und den button ggf. ganz ausblenden, wenn keine Moderation ausgewählt ist)

**Comment by jojo12** [comment]
Ah, das hat zu tun mit der Moderation von Neuen Usern?

**Comment by joomod** [comment]
...oder von Gästen (falls public frontend aktiviert ist)

**Comment by jojo12** [comment]
I am learning a lot new things 👍

**Comment by joomod** [comment]
ich schau mir den code mal an, vielleicht kann man ja sogar mit anzeigen ob Freigaben erforderlich sind?
(bei Null inaktiv ansonsten (1,2,3...x)

**Comment by joomod** [comment]
hat sich das mit der Schrift auch erledigt?
(ich finde nix)

**Comment by slabbi** [comment]
Das MCP Plugin dient zum Kontrollieren von Störern. Es darf nicht zum generellen Überwachen benutzt werden.
Wenn ein Konto überwacht wird, wird dem User auch eine entsprechende Meldung angezeigt.

**Comment by joomod** [comment]
ja, aber unter Nachrichten bearbeiten wird doch task=mcp aufgerufen ?
ich bin nämlich gerade am überlegen die beiden Infozeilen als Button darzustellen
(dort wird ja auch die Anzahl angezeigt) und die beiden MenuButtons ganz auszublenden?

**Comment by slabbi** [comment]
Ja ud nein, es erscheint ein Button, wenn das MCP installiert ist.
"Spam Control" und "MCP" arbeiten wie folgt:

"Spam Control":
Der Benutzer hat im Frontend einen Knopf mit der er eine Nachricht melden kann. Diese wird im Backend dem Admin in einer Liste angezeigt. Der Admin entscheidet, was damit geschieht.

"MCP":
Ein Konto mit diesem Flag wird moderiert.
Der User bekommt einen Hinweis angezeigt, dass das Konto moderiert wird, der Admin damit alles sieht, was er macht.
Sendet der Benutzer eine E-Mail, bekommt der Admin diese im Backend in einer Liste angezeigt. Dieser entscheidet, was damit zu tun ist.

Da muss kein zusätzlicher Botton etc. hinzugefügt werden.

**Comment by jojo12** [comment]
vielleicht wäre im Deutschen "Warnmeldung" für Report besser?

**Comment by joomod** [comment]
> Da muss kein zusätzlicher Botton etc. hinzugefügt werden.

ich meinte auch nicht zusätzlich, sondern einfach die **beiden Infozeilen**
(die bei installierten MCP und Spamcontroll angezeigt werden) mit class="btn..." versehen
und dann die beiden oberen **buttons im Menu ausblenden**/weglassen.

die ganze Config ist schon sehr umfangreich, warum dann den Zugang zum Nachrichten/Meldungen Control
zweimal anzeigen? (es verbirgt sich ja immer derselbe link dahinter)

btw. wo/wie kann ein Admin/Moderator diesen "flag" setzen?
(ist es das **Mod** in den user-settings?)

**Comment by slabbi** [comment]
Ja, es ist Mod in den User Settings.

**Comment by jojo12** [comment]
joomod wrote:

> hat sich das mit der Schrift auch erledigt?
(ich finde nix)

nein, ich habe gesehen mit dem atum light template sieht man die Schrift, mit dem dark mode ist nur weiss auf weiss!

**Comment by joomod** [comment]
so, hab die Nachrichten und Meldungen buttons zusammengefasst, einfach mal testen und anschauen (2 Dateien)
[admin.zip](https://github.com/slabbi/uddeIM/files/15295483/admin.zip)

aktuell überarbeite ich noch die Meldbuttons im Postfach (ist ein bisschen raw style :)

**Comment by slabbi** [comment]
Ich bin mir nicht sicher, ob das sinnvoll ist. Ich habe schon lange kein Joomla mehr laufen, kann das so nicht beurteilen.
Die Toolbar Buttons hatten damals schon ihren Sinn. Kannst du mal ein Screenshot posten von Vorher/Nachher?

**Comment by jojo12** [comment]
@joomod: habs installiert und probiere:
@1: (Warn-)Meldung kommt, aber ich kann sie nicht anschauen, kann nur "Meldung entfernen", heisst das die "Warnung macht keinen Sinn"? oder "Nachricht löschen" weil es SPAM oder sonst was ist? Wenn ich sie aber nicht anschauen kann, wie soll ich dann beurteilen?
@2: Ich habe moderieren angestellt, aber ich erhalte keine Moderation mehr, die PM scheint direkt rauszugehen. (Nachricht von einem registrierten Benutzer, aber registrierte sollen moderiert werden.

**Comment by slabbi** [comment]
Ganz ehrlich, ich würde die Funktion so belassen, wie sie ist.

**Comment by joomod** [comment]
ich hab am **funktions** code eigentlich nichts geändert, nur bei den Informationszeilen class="btn ..." hinzugefügt
und die menubuttons nur auskommentiert.

alt
![uddeim-alt](https://github.com/slabbi/uddeIM/assets/149375504/28652716-db1c-4a1b-b773-239fbf605a1e)

neu
![uddeim-neu](https://github.com/slabbi/uddeIM/assets/149375504/d7201303-6cd1-42b1-a39a-2db43b727ce1)

@jojo  mit deinerAussage zu @1 komm ich nicht klar
oder meinst Du im frontend?
da gibt es zuerst: (=immer)  Nachricht melden
**wenn eine Nachricht gemeldet wurde** steht dann da:  "Nachricht gemeldet" (nur als Hinweis) 
                                                                                         und "Meldung zurückrufen" zum anklicken.
die Nachricht selbst bleibt solange sichtbar bis der Admin im backend etwas damit macht

**Comment by joomod** [comment]
@jojo habs gefunden.
ist im backend - du hast Recht, die gezeigte (gemeldete) Nachricht lässt sich nicht öffnen.
schau ich mir gleich an

**Comment by joomod** [comment]
hat irgendwas mit dem javascript:**uddeIMtoggleLayer()** zu tun unabhängig ob altes oder neues layout.
leider zeigt mir die Konsolole auch keinen javascript fehler
(im frontend funktioniert es problemlos)

**Comment by slabbi** [comment]
Könnte es sein, dass die Nachricht verschlüsselt abgelegt ist? In diesem Fall kann nichts angezeigt werden.

**Comment by joomod** [comment]
nein, ist eine normale Nachricht.
der code müßte ja irgendwo in admin.spamcontrol bzw mcp stehen?

**Comment by joomod** [comment]
du hast doch irgendwie Recht ???
die Nachricht steht zwar im Klartext in der Datenbank, aber über das query kommt sie verschlüsselt an ???
irgend eine Idee wieso

**Comment by joomod** [comment]
gefunden - war mein Fehler (hab beim Überarbeiten der crypt.class eine if Kette falsch interpretiert)
mit dieser Version sollte es gehen
[crypt.class.zip](https://github.com/slabbi/uddeIM/files/15299125/crypt.class.zip)

ist im main branch schon geändert

**Comment by slabbi** [comment]
Checkst du bitte noch die aus [admin.zip](https://github.com/slabbi/uddeIM/files/15295483/admin.zip) mit ein?

**Comment by joomod** [comment]
wollte gerade fragen :)  was haltet ihr von der neuen Button Läsung?
ich finds verständlicher (und oben wird es auch übersichtlicher)

- also soll ich es so ändern?

**Comment by slabbi** [comment]
Für mich ok

**Comment by joomod** [comment]
alles klar - mach ich dann mal

**Comment by slabbi** [comment]
closed

**Comment by jojo12** [comment]
super, das kann man gebrauchen.
