### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#64]
Ich frage nochmals, weil ich es immer eigenhändig ändern muss:
Problem: bei mir und anderen, kommen mit dem Original includes.php alle Mails aus uddeIM in SPAM-Ordner, sogar mit Whitelist.
Dann erhält man die Mitteilung aber nur durch Zufall!

es ist gut, wenn ich folgendermassen ändere:
change line 125: from `$temp = '"'.$fromname.'"';`  to `$temp = $fromname;`      [das ist doch zu viel]
AND
line 130-134 ausklammern

Ihr müsst Gründe haben, warum ihr es so lasst. Landet es bei Euch nicht im SPAM?

**Comment by slabbi** [comment]
"From" should be without quotes -> changed
Lines 130-134 should not be removed as these typically prevent messages from being classified as spam.
I changed the User-Agent now to "uddeIM PMS". All other lines should not be changed especially the character encoding.

**Comment by jojo12** [comment]
bei mir stimmts trotzdem noch nicht, sorry. Weshalb landet es bei euch nicht im SPAM?

**Comment by slabbi** [comment]
Das kann mehrere Gründe haben. Meistens liegt es daran, dass Joomla auf einem Shared Server läuft und von dort doe E-Mails versendet werden. Dann fallen mehrere Gründe zusammen: 1. Andere Instanzen auf dem Server können dafür sorgen, dass der Server in verschiedenen Blocking Lists gelistet ist; 2. Du selbst sendest unter Domäne XY deine E-Mails, der Server hat aber eine andere Domäne YZ (da shared).
In Falle eines Shared Servers sollten sie Nachrichten immer authentifiziert über den MTA des eigenen Providers geschickt werden.

**Comment by jojo12** [comment]
danke, ich gebe auf und mache es eigenhändig.
Ich habe sonst nie Probleme mit SPAM.

**Comment by jojo12** [comment]
übrigens widerspricht sich das "reply to" mit der Meldung "loggen sie sich ein, um auf die Mitteilung zu antworten"
wenn das nicht ausgeklammert ist, kann ich direkt aus der Email antworten, was nicht gewünscht ist.

**Comment by slabbi** [comment]
Wo ist denn das Problem?

Die geänderte "From"-Zeile ist nachvollziehbar. Die ist im main vorhanden. Auch der "User Agent" hat sich geändert.
Du kannst gerne weitere Änderungen vornehmen, damit es bei dir funktioniert. 

Aber das Character Encoding wegzulassen ist keine Lösung, da viele andere User dann Probleme hätten.

Die Spam Probleme tauchen meistens dann auf, wenn die PHP Funktion mail zum Versenden verwendet wird. Die Gründe stehen in den Quellen meines vorherigen Posts. Das lässt sich auf uddeIM Seite nicht fixen. Wenn du dir Nachrichten per SMTP versendest, sollten diese durchgehen, vorausgesetzt der Server steht nicht auch auf einer Blocking List.

**Comment by slabbi** [comment]
> übrigens widerspricht sich das "reply to" mit der Meldung "loggen sie sich ein, um auf die Mitteilung zu antworten"
> wenn das nicht ausgeklammert ist, kann ich direkt aus der Email antworten, was nicht gewünscht ist.

Wenn du noch eingeloggt bist, merkt sich der Browser dieses.
Schließe einmal den Browser und klick dann auf den Link, dann passt es.

**Comment by jojo12** [comment]
stimmt, ich kann nur mit php mail senden, sonst erhalte ich in der Grundeinstellung eine Fehlermeldung.

**Comment by jojo12** [comment]
Herzlichen Dank für Eure Mithilfe. Habe gelernt, dass SMTP besser ist und via meinem Hoster das ganze von php mail auf SMTP 
umgestellt. Auch in uddeIM. Nun kommt alles in Posteingang. DANKE FÜR EURE GEDULD!

**Comment by slabbi** [comment]
Kein Problem. Wenn du eine eigene Domain einsetzt, solltest du auch einmal bzgl. SPF und DKIM nachlesen.
Alles hilft dabei, dass deine E-Mails nicht mehr als Spam erkannt werden, aber auch andere nicht unter deiner Domain Spam versenden können.
