### ISSUE TITLE
just some styling for spamcontrol in postbox/inbox

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#65]
as the spamcontrol notice lines come very raw I have edit the code to add some styling
(not very much, but just a little to be different from the rest)
![melde2](https://github.com/slabbi/uddeIM/assets/149375504/7fcd2a4b-e1d4-449b-b036-cad62ee9a295)
![gemeldet2](https://github.com/slabbi/uddeIM/assets/149375504/32e5e678-cad2-4c73-980f-b08c2a4accec)
![gemeldet](https://github.com/slabbi/uddeIM/assets/149375504/775ecfc9-b315-4748-a43f-c6c6204ab5b8)
![melde](https://github.com/slabbi/uddeIM/assets/149375504/f7cb0345-c0f9-4996-b479-75f40dba1d11)

**changed files**
[post+inbox.zip](https://github.com/slabbi/uddeIM/files/15305916/post%2Binbox.zip)

if you find it better than old raw I will look to do this in css (without inline-css)

**Comment by jojo12** [comment]
for me it's about the same. So others (or you) have to decide.
Meanwhile I am used, that this is "Meldung" .
Thank you for your efforts.

**Comment by slabbi** [comment]
Styling ist immer net. Aber in den "templates". ;)
