### ISSUE TITLE
another styling: backend userlist

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#66]
as the limit dropdown comes from joomla the rest of udd-dropdowns look a bit old-stylish,
so I try to switch all to the joomla "form-select" class, which is bigger, so 2 lines are needed.

![usersetalt](https://github.com/slabbi/uddeIM/assets/149375504/e9162342-48dd-439d-a004-36f3dee864ee)
![userset](https://github.com/slabbi/uddeIM/assets/149375504/83a371a6-e0ea-4569-9fb0-b37b9d253c1b)

which one looks better?

**Comment by slabbi** [comment]
Personally I do not like large buttons for filtering only. They take up too much space without having an important use.

**Comment by jojo12** [comment]
wieder geöffnet, wegen Problem Schriftfarbe (color) bei userlist
admin template ATUM arbeitet mit der Möglichkeit in dark mode zu schalten, bzw. zwischen dark mode und light mode zu switchen. (Wenn du im template ATUM bei Farben auf dark mode setzt, gibt es rechts oben im Benutzermenü den Switcher: Dark mode und Light mode.) Dann siehst du, dass man die Schrift nur im Light mode sieht.
Meine Erfahrung: ab linie 39 in table.adminlist td ergänzt mit color: #000 ist bei beiden Modi gut!
So wie es jetzt ist, ist es schlecht!

**Comment by joomod** [comment]
du meinst schon die Seite "ändere Benutzereinstellungen" und gemeldete bzw. mod. Nachrichten?
das könnten wir in der css tabel.adminlist mit color #555 (oder 333) fixen

**Comment by jojo12** [comment]
ja, genau, die beiden Vorschläge sind auch gut!

**Comment by joomod** [comment]
ok, schreibe ich in die admin.uddeim5.css 
(color:#444) - die goldene Mitte :)

**Comment by joomod** [comment]
done
