### ISSUE TITLE
zum testen: Styling pack

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#69]
hab jetzt div kl. Änderungen (haupsächlich classnamen) gemacht und dann entspechende **css Ergänzungen** um
im backend und bein den Spammeldungen etwas mehr modernes design zu erhalten
(userlist buttons sind jetzt kleiner :), aber im modernen joomla style)
die CSS Dateien sind hier **erstmal** nur für das **default** template

[styling.zip](https://github.com/slabbi/uddeIM/files/15333455/styling.zip)

![userlist](https://github.com/slabbi/uddeIM/assets/149375504/597f3b03-c525-438e-b3cd-871a83661844)
![spam-mcp](https://github.com/slabbi/uddeIM/assets/149375504/c4389676-7a9f-480e-958c-e50d36e77076)
![postbox](https://github.com/slabbi/uddeIM/assets/149375504/0b6111f1-f305-4848-ae1b-5d8919d727b6)

**Comment by slabbi** [comment]
Was passiert, wenn man auf ein anderes Template umschaltet?
Die CSS Änderungen sind vermutlich für das default Tamplate korrekt?
Die Änderungen in den php Dateien werden aber alle Templates beeinflussen, oder?

**Comment by joomod** [comment]
jaja, wenn es so passt muß ich die Zeilen natürlich überall einfügen 
(wollte ich mir zum Anschauen erst mal sparen :)

**Comment by slabbi** [comment]
Dann mach mal :)

**Comment by joomod** [comment]
templates finished.
can you please add them (just the uddeim.css of **each theme**)

[templates.zip](https://github.com/slabbi/uddeIM/files/15399760/templates.zip)

**Comment by slabbi** [comment]
comitted

**Comment by joomod** [comment]
just checked, :(
the uddeim.css must be copied in the **css folder**,  (override the old file)
you (or may be how I created the zip) just stored them in the **main template folder**

**Comment by slabbi** [comment]
done

**Comment by joomod** [comment]
thank you
