### ISSUE TITLE
Question: Verstecke Benutzer enthält von Anfang an: 62

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#70]
Das war glaub ich früher mal so, dass id: 62 der Administrator war.
Das hat sich aber m.E. geändert. Deshalb kann es stören, wenn diese 62 automatisch gesetzt ist!
Hab ich recht?
Verwaltung>Darstellung>Verstecke Benutzer

**Comment by slabbi** [comment]
Keine Ahnung ;) @joomod ?

**Comment by joomod** [comment]
was früher war weis ich nicht :)
aber ich kann die 62 auch aus der config weglassen
(ich weis nicht ob man in joomla die IDs der SAadmins auslesen kann)

**Comment by jojo12** [comment]
Bei mir war ein alter Hase, der hatte wirklich id=62. Er hatte Probleme, bis wir die 62 aus dem Feld gelöscht hatten!

**Comment by joomod** [comment]
ich denke die **2.Lösung** macht Sinn - oder?
muß ich dann in der config.class und im install script anpassen

**Comment by slabbi** [comment]
Durchaus.
Die config.class aber nur so anpassen, dass hideusers und pubhideusers leer sind.
Im Install-Script könnte die ID dann bestimmt werden und bei der Erstinstallation hineingeschrieben werden.

**Comment by joomod** [comment]
das mit der config.class habe ich mir gerade auch gedacht

**Comment by slabbi** [comment]
Folgendes geht leider nicht:
  var $hideusers = _suser;
  var $pubhideusers = _suser;
Die Variablen können auch mehrere IDs enthalten.
Ich würde auch vorschlagen, keinen Code wie
 define('_suser', Joomla\CMS\Factory::getApplication()->getIdentity()->id);
in diesem File zu verwenden.

**Comment by slabbi** [comment]
... und mit
define('_suser', Joomla\CMS\Factory::getApplication()->getIdentity()->id);
könnte der Benutzer keine IDs mehr konfigurieren.

**Comment by joomod** [comment]
ich habs in der config.class jetzt auf = '' gesetzt 
und nur im install script mit Factory::getApplication()->getIdentity()->id eingefügt

**Comment by slabbi** [comment]
Soll ich die einchecken? Alles ok?

**Comment by jojo12** [comment]
ich weiss nicht, was das im install script macht. Aber dass es leergelassen wird, ist gut.

**Comment by joomod** [comment]
die config und script kannst Du gern einchecken,
bei den anderen will ich erst die ganz template files machen

**Comment by slabbi** [comment]
ok, done

**Comment by joomod** [comment]
die anderen php Dateien gehen natürlich auch schon  (sind ja nur class Ergänzungen), also
- admin.mcp.php
- admin.spamcontrol.php
- admin.usersettings.php
- toolbar.uddeim.php

wenn ich die css files fertig habe lade ich sie hoch

**Comment by slabbi** [comment]
done

**Comment by joomod** [comment]
kannst Du dich noch erinnern, weshalb Du die admin.uddeim.css jeweils pro template abgelegt hast
(ein im admin Verzeichnis würde doch genügen ?)

**Comment by joomod** [comment]
sind ja alle bis auf eine winzige Ausnahme gleich (und die greift nicht mehr weil die J pagenav classes anders sind)
ich bau die Ladefunktion um und ergänze bei den templates einen admin Ordner
(+ zur Sicherheit wird die admin.css auch im admin Ordner mit abgelegt)

**Comment by joomod** [comment]
**admin.uddeim.css** inkl. div Änderungen (admin Verzeichnis in template folder, load in admin.uddeim.php) integriert
(wird/kann aus den einzelnen templates gelöscht werden)

**Comment by slabbi** [comment]
In früheren Joomla Versionen konnte man das Backend separat stylen, also dem Template entsprechend anpassen.

**Comment by joomod** [comment]
würde schon noch gehen, aber wer macht das schon und ist halt für css updates ein mühsamer Aufwand.
im backend geht es ja hauptsächlich um Größen und Platzierung u. vielleicht etwas bootstrap
ein aufwendiges Styling würde die Arbeit im backend eher verschlechtern 
ich find eine css fürs backend reicht vollkommen :)

**Comment by joomod** [comment]
habe gerade noch die Struktur der Kopftabelle etwas umgestellt (bereits im code)

![backend](https://github.com/slabbi/uddeIM/assets/149375504/d179dc19-3a07-4770-9c7c-3a00df57acc5)

**Comment by joomod** [comment]
@slabbi 
you checked in some old admin.usersettings.php ?
I renamed this (old) and uploaded the actual, new file
