### ISSUE TITLE
Dateianhang bei Rückruf einer versendete Nachricht verschwunden

### ISSUE THREAD

**Issue by ManKalusch** [slabbi/uddeIM#71]
Joomla: 5.1.0
uddeIM: v5.3

Wenn man in einer Nachricht eine Datei (z. B. Bild) anhängt und die Nachricht nach dem Absenden zurückholt, dann "verschwindet" der Dateianhang.

**Comment by ManKalusch** [comment]
PS: Es gibt ja den Nachrichtenpunkt "Datei auswählen". Aber einen wie "Datei entfernen" gibts nicht, wenn man sich bei der Datei vertan hat.

**Comment by slabbi** [comment]
Das ist korrekt. Wenn die Nachricht zurückgeholt wird, wird der Anhang sofort gelöscht, sonst müsste man eine Referenz behalten und abwarten, was der User als nächstes macht. Wenn er den dann aber den Browser schließt, bliebe diese "Leiche" erhalten.

Datei entfernen ist nicht vorhanden und produziert eine "Leiche", wenn die Nachricht nicht verschickt wird. Es gibt aber einen "Aufräumprozess", der dieses beseitigt.

**Comment by ManKalusch** [comment]
Aaa. OK. Dieser Hintergrund war mir nicht bekannt. Also, wenn sich der User vertan hat, dann einfach die Nachricht zurückholen und die richtige Anhängen.

Danke für die Erläuterung.
