### ISSUE TITLE
com_uddeim_j5 latest error: 0 syntax error, unexpected variable "$css" 

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#72]
# | Function | Location
-- | -- | --
1 | () | JROOT\administrator\components\com_uddeim\admin.uddeim.php:110
2 | require_once() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:71
3 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT\libraries\src\Dispatcher\LegacyComponentDispatcher.php:73
4 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:361
5 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:150
6 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:195
7 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:306
8 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:58
9 | require_once() | JROOT\administrator\index.php:32

**Comment by slabbi** [comment]
Seems to be introduced with @joomod css changes.
A ")" was missing.
Fixed.

**Comment by joomod** [comment]
yes, sorry, 
but not the bracket was missing it was a double file_exsits function (copy&paste is easy but danerous :))

**Comment by slabbi** [comment]
It was. See here

![grafik](https://github.com/slabbi/uddeIM/assets/65805263/24b79173-a272-45e5-95ec-55efbb5ed56f)

**Comment by joomod** [comment]
exactly, but you can also see the double file_exists :) which was my real error
