### ISSUE TITLE
config style update finished

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#73]
after correcting css path error everything now should work.
I restyled the backen config with a more modern looking (eg. radio buttons)

the files are already commited
(besides my "bracket" error there are no php code changes, only classes and the admin.css)

- sorry, the template css for the spamcontrol messages are **not ready** yet

![config](https://github.com/slabbi/uddeIM/assets/149375504/8e6920da-104e-4143-8f36-46388ee40c7f)

**Comment by joomod** [comment]
ich hoffe dass das neue layout so gefällt?

ich wollte halt ein bisschen modernen Anstrich ins backend bringen,
und da sind radio-buttons schon länger nicht mehr 'state of the art' :)

(die ganz aktuellen Ja/Nein switches habe ich bewußt nicht gewählt, da die
Einstellungen bei so einem umfangreichen config nicht so klar rüberkommen.
+ außerdem wäre das viel komplizierter gewesen über layout etc. :)

**Comment by jojo12** [comment]
ja gefällt mir. Danke.

**Comment by joomod** [comment]
wenn das so bleiben kann müßten aus den **einzelnen** 
templates die **admin.uddeim.css** **gelöscht** bzw. upgedated werden.

**Comment by slabbi** [comment]
Dann mach mal ;)
Ich hatte die eine Weiche eingebaut:
Wenn eine CSS im template Folder vorhanden ist, dann nehme diese, wenn nicht, dann die aus dem Admin Ordner.
Danach alle individuellen admin.uddeim.css löschen, die nichts zum Styling beitragen.

**Comment by joomod** [comment]
Weiche hab ich auch, aber ich hab sie gerade nochmal um einen check in den templates erweitert,
so bleiben alle Möglichkeiten offen.
die alten css in den templates habe ich gelöscht, aber wenn jemand will kann man eine spezielle ablegen

**Comment by ManKalusch** [comment]
Das neue Aussehen gefällt mir auch!!
