### ISSUE TITLE
Question: never seen before: admin.uddeim.php: radiobutton AND yes/no fields

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#74]
Das habe ich noch nie gesehen und verstehe es daher nicht: diese "Verdoppelung" der Einstellung. Ist das üblich, oder ein Gag? Was ist der Vorteil?
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/98e72a8c-0384-4bef-b77e-fb3b66b60c21)

**Comment by joomod** [comment]
da fehlt die css,
in der Version mit dem Klammerfehler war der css-Pfad falsch.
bitte verwende diese  (ist auch hier so geändert)
[admin.uddeim.zip](https://github.com/slabbi/uddeIM/files/15368849/admin.uddeim.zip)

**Comment by jojo12** [comment]
jetzt ists ok! Danke

**Comment by joomod** [comment]
sollte ungefär so aussehen wie in der doku
https://github.com/slabbi/uddeIM/issues/73

**Comment by jojo12** [comment]
ich hatte es heute morgen aus dem main installiert und dann das erste Resultat erhalten.
mit dem Anhang hier siehts gut aus. Ist der ins main übernommen?

**Comment by slabbi** [comment]
Da war noch eine Änderungen bei
uddeIMadmText($config->pubhideusers,...
ich habe diese jetzt eingecheckt.

**Comment by joomod** [comment]
ich hoffe dass das neue layout so gefällt?

ich wollte halt ein bisschen modernen Anstrich ins backend bringen,
und da sind radio-buttons schon länger nicht mehr 'state of the art'  :)

(die ganz aktuellen Ja/Nein switches habe ich bewußt nicht gewählt, da die 
Einstellungen bei so einem umfangreichen config nicht so klar rüberkommen)

**Comment by joomod** [comment]
@slabbi 
wieso hast Du den Wert bei pubhideuser wieder auf 20 zurückgesetzt?
(ich brauche die 10 damit das postfix 'ID' noch ins layout passt)
aktuell wieder geändert auf 10

**Comment by slabbi** [comment]
Ich habe die Datei aus deinem Anhang oben eingecheckt.

**Comment by joomod** [comment]
**huch**, dann war das bei der auch noch falsch

**Comment by jojo12** [comment]
Habe aus der main ein Paket gemacht 19.05.2024, 18:50 Uhr und installiert. da war das richtige admin_uddeim.php nicht integriert.
hatte wieder radio buttons und ja/nein gruppe!

**Comment by joomod** [comment]
wenn Du nur die admin.uddeim.php kopiert hast klappt es nicht.
nach slabbis Vorschlag hab ich die Weiche erweitert, damit sie 
**zuerst** in den templates Verzeichnissen nach der css sucht.
als **zweites** dann in dem neuen templates/admin Ordner
und ggf. noch im admin Verzeichnis.

du mußt also die **admin.uddeim.css** aus den einzelnen Ordnern (nicht admin) **löschen!**

**Comment by jojo12** [comment]
ist das nur für mich so, oder müssen alle, die uddeIM UPDATEN, die admin.uddeim.css MANUELL löschen?
Und wie ist es bei einer NEUINSTALLATION?

**Comment by joomod** [comment]
bin selber gerade darüber gestolpert :)
werde die admin.uddeim.css in admin.uddeim5.css ümbenennen
und dementsprechend auch nach dieser suchen, d.h. sie wird in den templates nicht gefunden
(alte admin.uddeim.css akzeptiert das script dann ja nicht und müssen nicht gelöscht werden)
Eigenkreationen müssen dann halt auch admin.uddeim5.css heißen.

außerdem werde ich für die template Liste den admin und License Ordner ausblenden

**Comment by joomod** [comment]
I think can be closed
