### ISSUE TITLE
Captcha Service ->Internal

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#75]
Es gibt die Möglichkeit ein Internes Captcha System zu wählen, es wird dann auch ein Sicherheitscode abgefragt. Aber wie komme ich zu diesem?

Es fehlen hier auch deutsche Übersetzungen!

"Which captcha service do you want to use: The build-in service or reCaptcha (see [reCaptcha](http://recaptcha.net/) for more information)?"	
"When you want to use reCaptcha, enter your public key here."	
"When you want to use reCaptcha, enter your private key here."

**Comment by joomod** [comment]
da ist noch der alte link zu recaptcha.net, das ja mittlerweile von google übernommen wurde
https://www.google.com/recaptcha/about/

aber ehrlich gesagt habe ich es in uddeim noch nicht wirklich getestet

**Comment by jojo12** [comment]
recaptcha 2.0 geht!

**Comment by joomod** [comment]
edit new links and german in main

**Comment by joomod** [comment]
hast Du auch mal die interne Funktion getestet?

**Comment by jojo12** [comment]
wenn du mich fragst. Ich sprach am Anfang mit der "internen Funktion" die nicht funktioniert.
Es stellt sich auch die Frage, was ist die "interne Funktion":
a) ein uddeIM internes/eigenes Captcha?
b) das in Joomla Settings gewählte Captcha?

**Comment by jojo12** [comment]
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/553838ce-0108-45bb-a170-441757c900f1)

**Comment by joomod** [comment]
da ist eine eigene catcha library, die mit hochgeladen wird.
Ich habe sie noch für die v5.3 mit der aktuellen version upgedated (so wie auf desse github veröffentlicht)

ah, sehe gerade in dem Bild den Code den Du meinst
(ich dachte Du meinst die reCaptcha keys)

**Comment by joomod** [comment]
sodele, ein bisschen schlauer.
da sollte eigentlich ein Bild erscheinen was von der Datei captcha15.php erzeugt wird,
aber die funktioniert wohl nicht (habe ich mir scheinbar auch nie näher angeschaut, noch kein J5 code)

**Comment by jojo12** [comment]
Ja, mensch staunt, was es da noch alles hat :-)

**Comment by slabbi** [comment]
Da ist nicht viel Joomla Code drin
Vermutlich eher ein PHP 8.x Problem

**Comment by slabbi** [comment]
Gerade nachgeguckt: Hat sich geändert:
Probiere:
$session = JFactory::getSession();
$session->set('security_code', $code);

**Comment by joomod** [comment]
Bild hab ich schon,
jetzt muß ich schauen/prüfen ob der code
richtig gespeichert wird

**Comment by joomod** [comment]
so, interes captcha sollte jetzt auch gehen (main breits updated)
- captcha15.php **gelöscht**
- captcha.php   **neu**
- includes.php   **update**  (wichtig, ohne diese Version wird captcha15 aufgerufen)

(in der zip ist meine includes.php vom testen, bin mir aber nicht sicher ob die vorher
auf dem aktuellsten Stand war, also besser die version aus der main laden)
[captcha.zip](https://github.com/slabbi/uddeIM/files/15441967/captcha.zip)

**Comment by slabbi** [comment]
Nicht ernsthaft:
$captchalen = $_GET['clen'];
So kann ein Spammer einfach einen kürzeren Captcha Code mitliefern. Evtl. würde auch "0" funktionieren.
Bitte die Config-Class weiterhin laden. Das ist ist kein Problem hier.

**Comment by slabbi** [comment]
Ich habe die eingecheckten Dateien bzgl. Captcha aufgrund einer möglichen Schwachstelle zurückgesetzt.
Bitte noch einmal genau ansehen, gerade wenn das Framework manuell geladen wird.
Die Config-Datei sollte auch wieder geladen werden und nicht auf übergebene Parameter im HTTP Header achten.

**Comment by joomod** [comment]
jetzt klär mich mal auf:
wie soll denn ein Spammer an den **internen** Aufruf der captcha.php kommen?

**Comment by joomod** [comment]
ok, habs gerade ausprobiert, geht mit dem config Aufruf genauso
(hatte da beim testen öfters Probleme)

könntest Du die updates **wieder einpflegen** ?
(die zwei config Zeilen sind ja in der captcha.php nur auskommentiert,
lediglich die variable müßte wieder $config->captchalen heißen)

**Comment by slabbi** [comment]
Nein, leider nicht. Bitte korrigiert wieder einchecken.

**Comment by joomod** [comment]
ok, done

**Comment by joomod** [comment]
nur zur Info (und nachlesen :):
Hauptproblem war der geänderte Aufruf des Joomla framework:
aktuell (5) sieht es so aus:

`define("_JEXEC", 1 );
define( 'JPATH_BASE', realpath(dirname(__FILE__).'/../..' ));
if (!(defined('_JEXEC'))) { die( 'Direct Access to this location is not allowed.' ); }

require_once ( JPATH_BASE .'/includes/defines.php' );
require_once ( JPATH_BASE .'/includes/framework.php' );

$container = \Joomla\CMS\Factory::getContainer();
$container->alias(\Joomla\Session\SessionInterface::class, 'session.web.site');

$app = $container->get(\Joomla\CMS\Application\SiteApplication::class);
\Joomla\CMS\Factory::$application = $app;
$app->createExtensionNamespaceMap();`

und dann:  `$session = Joomla\CMS\Factory::getApplication()->getSession();`

**Comment by joomod** [comment]
@slabbi 
kennst Du eine Möglichkeit den img link (src=".../captcha.php")
irgendwie mit javascript erneut aufzurufen um ein anderes Bild neu  zu laden ?

(**jquery**.load könnte gehen, ist ja aber offiziell nicht geladen)

**Comment by slabbi** [comment]
Mit der derzeitigen Implementierung nicht möglich. Ich würde dann eher empfehlen, das Joomla Captcha zu unterstützen (unterstützt es Neuladen)? Als ich das Captcha implementiert habe, gab es das in Mambo bzw. Joomla 1.0 noch nicht.

Wobei bei
define("_JEXEC", 1 );
define( 'JPATH_BASE', realpath(dirname(__FILE__).'/../..' ));
if (!(defined('_JEXEC'))) { die( 'Direct Access to this location is not allowed.' ); }
...
die if-Abfrage entfallen kann.

**Comment by joomod** [comment]
schon logisch,
ich hab sie nur eingebaut weil JED checker immer danach schreit :)
------
mit jquery wäre ich ja fast soweit, aber
gibt es irgendeine Möglichkeit die als String zurückgegebenen Daten 
von imagejpeg wieder in ein Bild zu konvertieren?

**Comment by joomod** [comment]
dasa Joomla captcha schau ich mir mal an,
vielleicht kann man damit das veraltete Recaptcha 1 ersetzen

**Comment by joomod** [comment]
bis dahin komme ich :)
src="�����JFIF��`�`�����>CREATOR: gd-jpeg v1.0 (using IJG JPEG v62), default quality
���C�		

 $.' &quot;,#(7),01444'9=82<.342���C
usw.

**Comment by slabbi** [comment]
Willst du ein Bild inline verwenden?
https://www.w3docs.com/snippets/html/how-to-display-base64-images-in-html.html

**Comment by joomod** [comment]
genau darüber denke ich gerade nach

**Comment by jojo12** [comment]
I don't get any security images, only the question "security code"

**Comment by joomod** [comment]
have you installed the very actual versions?
captcha.php  (not captcha15)
includes.php

should look like this

![capimg](https://github.com/slabbi/uddeIM/assets/149375504/ea0a82aa-1438-4cd8-a3fc-a4bff2afa067)

**Comment by jojo12** [comment]
I always downloaded the whole main and made then a zipfile from com_uddeIM_J5, installed, cleaned caches and tried. Will do it again. (Now I know how it should be!)

**Comment by joomod** [comment]
I'm still working on a reload function.
using jquery it would be ready, 
but now try to get this in simple js

**Comment by jojo12** [comment]
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/2c7c7068-9e75-422c-b06f-38331395d790)
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/46200655-1a3e-4dee-9d25-6e0c72308080)

**Comment by jojo12** [comment]
with https://yoursite.ch/components/com_uddeim/captcha.php (I set the name of my site!)
I get a white page (no error lines) only white!

**Comment by jojo12** [comment]
I tried with public, I then get this: and it looks for captcha15
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/25eae8ee-9db7-4979-8f94-ab1ada541de5)

**Comment by joomod** [comment]
oh, thanks for that, havn't realized tha pubfrontend uses his own script.
- but not your missing image

have you looked in the inspector what this line looks like on regular use?

**Comment by jojo12** [comment]
when I try with registered, it looks for captcha.php which can not be loaded
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/caf16816-a115-4c6c-82f9-06d81ef13c6b)

**Comment by joomod** [comment]
there is an error in captcha.php (my fault) - forget comment slashes

can you edit (line 77 +/-)
` $session->set('security_code', strtolower($code)); just save lower case`
just add //
` $session->set('security_code', strtolower($code)); **//**just save lower case`

and the try again please

**Comment by jojo12** [comment]
yes, that's it in regular I have now an image with security code!

**Comment by joomod** [comment]
fine, in the meanwhile I have edit the pfrontend.php too.

but not finished yet (adding reload - a bit tricky)

**Comment by jojo12** [comment]
I tried pfrontend.php, it continues to search for captcha15.php

**Comment by joomod** [comment]
its the newest in main branch

**Comment by jojo12** [comment]
I downloaded it there (one file) and uploaded, but no result

**Comment by joomod** [comment]
may be only a chache problem.
I'm in pfrontend live and it calls captcha.php
(reset cache in backed)

**Comment by jojo12** [comment]
no I cached and cached again, I can't cache as cache can :-)

**Comment by joomod** [comment]
![Uploading captcha.PNG…]()

**Comment by jojo12** [comment]
yes, I see, but it continues to look for captcha.15.php (and even when I change in the inspector, it says "Bild kann nicht geladen werden"

**Comment by joomod** [comment]
just wait, could only be cache

**Comment by jojo12** [comment]
I purged the session the problem persists

**Comment by jojo12** [comment]
sorry, my fault: I was on my other site  oooh!
it works in public too!

**Comment by jojo12** [comment]
yes, the question is now, if the security code is always the same.

**Comment by joomod** [comment]
no, just reload

**Comment by joomod** [comment]
please try this  (reload option added)

also, in the before includes.php (now edited) was an error with security_code (strtolower)

[includes.zip](https://github.com/slabbi/uddeIM/files/15449235/includes.zip)

**Comment by jojo12** [comment]
this works fine now, thanks!
can be closed.

**Comment by joomod** [comment]
so do you think this is to be updated ?

**Comment by jojo12** [comment]
yes! wow!

**Comment by joomod** [comment]
ok, done (also in pfrontend)

I think we now can create a new release :)

**Comment by joomod** [comment]
I also **delete** the recaptcha option **v1**, as jojo stated v2 is working and v1 is out of date.
I don't try to include v3 or the new enterprise, as recaptcha is in security discussion.

may be somebody can help to include an option to select an "system installed" option 
(Joomla 5 itself has NO longer some integrated captcha option)

**Comment by joomod** [comment]
I included as 3rd possibility in config select - but not yet activated
**CB Antispam 5.0**
as uddeIM works in good collaboration with community builder,
may be users have installed this Antispam plugin,
but in the moment I don't know how to integrate it
(eg. I see there is a special kunena-Antispam plugin)

may be @**slabbi** can rollup his contact to Krillion of CB to get som help
(I think on CB side, they don't know yet, that there's a **v5 of uddeim ready**)

**Comment by joomod** [comment]
so, I **skipped** adding AntiSpam (only pay) or other plugin needing captcha systems,
instead I added a second internal, **numeric** captcha with a **hidden field** against robots,
based on kubik-rubik ECC (EasyCalcCheck Plus / Captcha)
I **don't added** new configs (max-number or disable hidden field, which should be used)

**test it** (only german included here, if you use en or fr download it fromk main)
[numcaptcha.zip](https://github.com/user-attachments/files/15508354/numcaptcha.zip)
