### ISSUE TITLE
help needed: php8.2 converting  config.class 

### ISSUE THREAD

**Issue by joomod** [slabbi/uddeIM#76]
as modern system (and Joomla) run with php8.2+
I have a deprecated message when converting the config.class.php

mainly the new addition  `$config->saveconfigdb = 0;`

so if the existing config doesn't habe saveconfigdb we must add it, but as from php8.2 we have
**_Creation of dynamic property  is deprecated_**

so how can I add this new property to the config.class

for the future I can simply define  uddeimconfigclass **extends stdClass** (stdClass allows dynamic properties) 
but the converting always uses an existing config.class

so what is the best way to handle this?

**Comment by slabbi** [comment]
Add to config.class.php,
change the code for writing the config file,
add a default when the properties are initialized.

**Comment by joomod** [comment]
understand, but writing the config string is not the problem,
but using your converting function, which will add new properties.
(but may be we can live with this on deprecated message :)

**Comment by joomod** [comment]
ok, added stdClass to config 2.8,
accept deprecated iif updating 2.6 to 2.8

close
