### ISSUE TITLE
Der Link zu den weiteren animierte Smileys ist ohne Wirkung

### ISSUE THREAD

**Issue by ManKalusch** [slabbi/uddeIM#79]
uddeIM 5.4 - config 2.8
Joomla 5.1.0

Wenn man "weitere animierte Smileys" in den Einstellungen aktiviert, erhält man einen weiteren Button. In der deutschsprachigen Ausgabe den Link "Mehr". Diese ist seit den Update auf 5.4 ohne Wirkung bzw. ist jetzt erst aufgefallen.

**Comment by joomod** [comment]
hmm, bei mir geht's
hast Du mal in der Konsoloe geschaut ob irgend ein JS _Fehller angezeigt wirs?
(ist ja ein js link)

**Comment by jojo12** [comment]
es ist eine Suboption: du musst animierte Smileys aktiviert haben, dann funktioniert auch weitere animierte Smileys!
(zumindest bei mir)

**Comment by joomod** [comment]
die Einstellung scheint ja richtig zu sein, - MEHR wird ja angezeigt,
aber das ist ein JS link (window open) - also muß ein JS Fehler vorliegen
(oder ist JS deaktiviert ?)

**Comment by jojo12** [comment]
ich kriege:
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/0b444c46-3e5b-4b90-9a2b-dfe9fff08405)

**Comment by ManKalusch** [comment]
"Animierte Smileys" und "Weitere animierte Smileys" sind aktiviert.

Mit der Konsole habe ich noch keine Erfahrungen. Hier mal, das was ausgeworfen wird, wenn man auf "Mehr" klickt:

Uncaught   private-nachricht?task=new:315
   ReferenceError: uddeimWindowOpen is not defined
    at HTMLAnchorElement.onclick (private-nachricht?task=new:315:191)

**Comment by joomod** [comment]
da steht genau das Problem das ich meine:
uddeimWindowOpen **is not defined**
schau mal in deinem Seitenquelltext ob dort diese Zeilen stehen:
`<script type="text/javascript">
</script>`

**Comment by ManKalusch** [comment]
Ja, alles da:

<script type="text/javascript">
</script>

**Comment by joomod** [comment]
das passt schon mal.
steht vor den Konsolen Zeilen noch was anderes?
es scheint halt so, als ob JS gestoppet wurde

**Comment by ManKalusch** [comment]
Erstmal Danke für deine Hilfe... Hilft das?
![Image1](https://github.com/slabbi/uddeIM/assets/150338473/99c38bf2-efd7-470a-98ab-d34837cc689a)

**Comment by joomod** [comment]
ok, das ist der Basisfehler:  SyntaxError stoppt JS
versuch mal rechts auf private-nachricht:269 zu klicken,
da müßte die Konsole in den entsprechenden Quelltext springen
(ggf. neu laden)

**Comment by joomod** [comment]
ist Deine Testseite schon öffentlich?

**Comment by ManKalusch** [comment]
Mal laienhaft gefragt: In der Zeile steht ja "Uncaught SyntaxError: **missing ) after argument list**". Also fehlt wohl eine abschließende Klammer - oder?

Im Quellcode der includes.php (Zeile: 1100) finde ich bei folgender rot unterstrichender Klammer keine Abschlussklammer:

![Image1](https://github.com/slabbi/uddeIM/assets/150338473/384ea46d-9ce4-4a5f-9435-70896936ce70)

**Comment by joomod** [comment]
ich kann das Bild leider nicht öffnen, aber die 
genannte Zeile muß so aussehen:
`echo("  uddeimWindow.document.writeln(\"<html><head><title>uddeIM<\/title>");`

**Comment by joomod** [comment]
PN kenne ich auch nicht.
kopier mir doch mal den Quellcode der Seite und lade ihn hoch
(ggf. auch als >Datei)

**Comment by ManKalusch** [comment]
OK. Hier der Quelltext, wenn man sich bei den Nachrichten befindet und auf "Neu" gegangen ist. Hoffe Du meinst mit Quellcode das:

[Seitenquelltext.txt](https://github.com/slabbi/uddeIM/files/15417449/Seitenquelltext.txt)

**Comment by slabbi** [comment]
Da ist doch die Klammer:

![grafik](https://github.com/slabbi/uddeIM/assets/65805263/afdb6404-80ab-4be1-922d-7bed4b8d2ba3)

**Comment by joomod** [comment]
**Problem gefunden - Ursache noch nicht:**

in dieser Zeile 
`uddeimWindow.document.writeln("<html><head><title>uddeIM<\/title><link href="https://www.record-art.de/components/com_uddeim`
wird durch die falschen doppelten Anführungszeichen **bei href**=  (und später auch mehr)
eigentlich die Argumentliste von writeIn abgeschlossen und deshalb die fehlende Klammer
als Syntax error ausgegeben.

schau mal in Deiner includes.php (uddeim) ob die Zeile ( +/- 1090) so aussieht:
`if(file_exists($pathtouser.'/templates/'.$config->templatedir.'/css/uddeim.css')) {
echo "<link rel='stylesheet' href='".$pathtosite."/components/com_uddeim/templates/".$config->templatedir."/css/uddeim.css' type='text/css' />"; }`

ich glaube aber es kommt von einem Plugin das du integriert hast, weil der link
`href="https://www.record-art.de/components/com_uddeim/templates/default/css/uddeim.css?80cfb7" rel="stylesheet" nonce="ZDVmYmJjMDM3NTA2MjFiMDA3OGU2MDQ2Y2FlNjNlODQ0MDBkYjA2MjczNzYyMTA3OWM1MTJlYWE4YjQ5MmJkNmQwYjYxYjg4YWY4NzVkM2EwYzg3Yjk2ZWM0MjdjY2NjNGQ2NjMyMWNiMmJjN2Q4MzcwM2IyNDhkOTQwNjhlOTE=" data-jtaldef-processed="2.0.11"/>`

im script nur so aussieht:
`href='".$pathtosite."/components/com_uddeim/templates/".$config->templatedir."/css/uddeim.css' type='text/css'`

das **_nonce_** und **_data-jtaldef-processed_** kommen durch **irgendein Plugin** ???

**Comment by joomod** [comment]
probiers mal mit diesen Zeilen in der includes.php
`echo('  uddeimWindow.document.writeln("<html><head><title>uddeIM<\/title>');
if(file_exists($pathtouser.'/templates/'.$config->templatedir.'/css/uddeim.css')) {
echo '<link rel="stylesheet" href="'.$pathtosite.'/components/com_uddeim/templates/'.$config->templatedir.'/css/uddeim.css" type="text/css" />';
}`
ich habs aber nicht live probiert, nur die Anführungszeichen gewechselt

**Comment by ManKalusch** [comment]
**Erstmal vielen, vielen DANK und Eure Geduld!!!**

Das "System-JT-ALDEF-PlugIn" hatte ein Update und durch Deaktivierung, funktioniert uddeim wieder!!

**Comment by joomod** [comment]
was sollt dieses plugin eigentlich bringen???
google-fonts und fontawesome lokal speichern ist ja sicher besser,
aber fontawesome ist ja schon lokal in joomla und die benötigten
g-fonts könnte man auch selbst downloaden

**Comment by ManKalusch** [comment]
Hast recht und die Installation ist auch nur "routinemäßig" erfolgt. Ich hatte mal - glaube ich - in der ct einen Bericht über externe Schriften nebst Problemen gelesen und bin dann auf dieses PlugIn gestossen, welches ich nun immer mitinstalliert hatte.

Hast aber recht. Es gehört nun der Vergangenheit an und ich bin grad am Ausmisten, was man mit dem neuen Joomla noch "braucht" und was nicht.

Entschuldigt, dass Euch daraus Arbeit erwachsen ist. Besten Dank nochmal! Ich alleine hätte es nicht rausgefunden.

**Comment by joomod** [comment]
ich denke dann können wir hier schliessen
