### ISSUE TITLE
Link to Forum gives error

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#80]
in one site, when integration>Show menu entry is enabled for kunena, the link gives an error. The link is 
https://www.mysite.ch/component/uddeim/index.php?option=com_kunena.

in an other site, the link is working and is:
https://www.mysite.ch/index.php?option=com_kunena

what can I do to get the right link?

**Comment by joomod** [comment]
das hängt oft mit den eigenen Menus zusammen.
wenn man Kunena im eigenen Menu nur als Alias einbindet sollte es gehen,
(wird so auch empfohlen)
wenn man dagegen das Forum direkt im Menu ablegt geht of was durcheinander.
(welche Kunena Version hast Du? 
- ich glaube in der allerneusten muß das Menu erst unter tools erstellt werden)

**Comment by jojo12** [comment]
die neuste ab 6.3

**Comment by joomod** [comment]
wurde da bei Dir das (spezielle) Kunena-Menu erstellt?  (bei mir nicht?)
ansonsten kannst Du es mal mit diesem Eintrag in der includes.php versuchen
(ca. Zeile 707)
**alt:**
`echo "<a href='/index.php?option=com_kunena'>";`
**neu:**
`echo "<a href='".$pathtosite."/index.php?option=com_kunena'>";`

**Comment by jojo12** [comment]
this works fine, thanks

**Comment by joomod** [comment]
@slabbi 
meinst Du ich sollte den Eintrag **so** ändern?

**Comment by jojo12** [comment]
Ich weiss nicht: ich hab nur auf der Site versucht, wo es klemmte 😉
