### ISSUE TITLE
CB Plugin Installation error

### ISSUE THREAD

**Issue by inLIMITit** [slabbi/uddeIM#81]
Hi, when trying to install the Community Builder Plugins via the CB Plugin Installer I get this Error Message:

`Upload fehlgeschlagen Die Datei "/joomla5/tmp/install_6652d62822efd/cb2_plug_pms_uddeim_j50/index.html" exsistiert nicht! Keine Speicherung Install CB Plugin wegen: Installation error `

Means, that there is an index.html missing?!

**Comment by joomod** [comment]
is already fixed for the new version
(just add some index.html to the zip)

**Comment by slabbi** [comment]
I will prepare a 5.4 release soon.
Please give feedback when the code is stable.

**Comment by jojo12** [comment]
I always only updated uddeIM, it must because of that, I never had this error!

**Comment by inLIMITit** [comment]
Thx, adding the index.php worked.

**Comment by joomod** [comment]
> I always only updated uddeIM, it must because of that, I never had this error!

don't remember:  :)
https://github.com/slabbi/uddeIM/issues/59
