### ISSUE TITLE
Permanent Pop up

### ISSUE THREAD

**Issue by inLIMITit** [slabbi/uddeIM#82]
When writing a new message with activated auto suggestion of receipent, I always get a pop up message when typing one single letter. When I close the window and type the next letter of the name, the pop up opens again. 
![IMG_6574](https://github.com/slabbi/uddeIM/assets/91622818/9e5120d4-be75-4439-9b35-a75ff5771894)

**Comment by joomod** [comment]
I will check this.
have you tried setting the delimiter to comma (config)?

**Comment by inLIMITit** [comment]
Yes, get the same pop up message (with comma).

**Comment by joomod** [comment]
is this within regular use or public frontend?

**Comment by inLIMITit** [comment]
Regular Use

**Comment by joomod** [comment]
check out this version (I actual use without popups)
[autocompleterW3.zip](https://github.com/slabbi/uddeIM/files/15447802/autocompleterW3.zip)

**Comment by inLIMITit** [comment]
When I download with Windows I get a warning for a virus / ransomware?

**Comment by slabbi** [comment]
Do you use a 3rd party virus scanner? It is a false alarm. 
The zip contains a javascript file for the autocomplete feature.

**Comment by inLIMITit** [comment]
No, it was the Windows 11 Scanner 😄

**Comment by inLIMITit** [comment]
Works fine, thx!
