### ISSUE TITLE
error 500 after update of latest com_uddeim (240531,17:10)

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#85]
Compile Error: Cannot redeclare numericcaptcha() (previously declared in /home/folktanz/public_html/components/com_uddeim/includes.php:1853)

**Comment by joomod** [comment]
let me asume, this is with punfrontend enabled?

**Comment by joomod** [comment]
numeric functions deleted in pfrontend (already loaded in includes.php)
should fix this bug
