### ISSUE TITLE
the read/unread icon should be better

### ISSUE THREAD

**Issue by jojo12** [slabbi/uddeIM#98]
it' s not good the envelope icon. You must try to change it with your mouse that it is read. And it's not easy, or you forget.
When I go to the message, the icon should change automatic (like earlier),
When you then want to change it back to unread (to get the new info) this should be possible.
a friend wrote:
`I still don't like the way the mailbox works. Clicking a new message shows the content, but does not mark it as 'read'. You have to click the stupid tiny little icon in the message itself to mark the message as read, or it will keep sending notifications. It's less intuitive as the old model.`

**Comment by ManKalusch** [comment]
Joomla: 5.1.1
uddeIM 5.4 - config 2.8

Nur zur Info:
Kann ich so nicht bestätigen. Bei mir funktioniert (2 Websites) es einwandfrei. Wenn man auf eine neue Nachricht klickt, wird diese automatisch als "gelesen" markiert.

**Comment by jojo12** [comment]
Ja, aber könnte es nicht nach einiger Zeit automatisch auf gelesen gehen (wenn du in der Mitteilung bist) und du nur bewusst auf "ungelesen" zurückstellen musst.
Es scheint zumindest an anderen Orten (oder sogar in früheren uddeIMs  so zu gehen.

**Comment by slabbi** [comment]
Sobald die Nachricht geöffnet wird, wird das Read-Flag gesetzt. Das ist mMn auch das sinnvollste Verhalten.

**Comment by jojo12** [comment]
jetzt ist es aber so, dass es händisch gesetzt werden muss!

**Comment by slabbi** [comment]
Evtl. noch ein Bug wg. J5 oder PHP 8?

**Comment by joomod** [comment]
bei solchen Nachrichtenproblemen bitte immer dazu **mit angeben**
welche Einstellung aktiv ist:  **Postxox**  oder **In/Out**

Ich denke du beziehst es auf die Postbox, da wird das read-icon tatsächlich nicht
durch das blose anklicken (expand) der Nachricht geändert.
Ich schau mal ob man da was mit einbinden kann.
Ich versuch auch mal das unread-icon als blinkend zu gestalten

**Comment by jojo12** [comment]
Ja postbox

**Comment by joomod** [comment]
sodele,
much work, but hopefully should do what you expect.

I added a new JS function to the readcell (and also flagcell)

now the switch from unread to read (also unflagged to flagged) is done inline
(no more page reload)
the unread switch is done by click on the read pic **OR click to open** the collapsed massage.
**unread** messages **always stay collapsed**, independent from the config setting (showpostboxfull)

I also added this inline script to the basic **inbox / outbox**

also there are new **blink icon** for unread messages (the old new_im is just used in outbox)

update also includes new css and **btn style** for the message info links (reply to...)

in the zip file you find all updated files which you must replace to test.
some templates are added, but not all - **only use these** for testing.

I hope I have remembered all changes, 'cause I must update the actual files with 
the script of my test setup.

[com_uddeim_j50new.zip](https://github.com/user-attachments/files/15925553/com_uddeim_j50new.zip)

try it

**Comment by slabbi** [comment]
Please also update the repository when tested (or send me a zip with all relevant files).

**Comment by jojo12** [comment]
How do I install this,
I get:
Warnung
JInstaller: :Install: Die XML-Installationsdatei konnte nicht gefunden werden.

**Comment by joomod** [comment]
its not an install zip
you must copy files manally to your folder (site / languages to admin)
(only some updated files are in zip)

**Comment by jojo12** [comment]
But I see files twice. so which one?

**Comment by joomod** [comment]
yes sorry, you are so fast :)
in the first upload there was also a site folder (now deleted)
just use the files from the main folder

**Comment by joomod** [comment]
p.s.
the flagged and unread icon in the postbox overview are linked to that message,
(or the message with the highest ID if there are more)
so it would open the box and jump to this, 
but the jump **only works** if the message is on the **first site** of the user's box 

so this is not a bug, but could not be controlled :(

**Comment by jojo12** [comment]
I get: in mailbox

> Warning: Undefined variable $flagtitle in C:\xampp\htdocs\joomla\components\com_uddeim\uddeim.php on line 239

Warning: Undefined variable $unflagtitle in C:\xampp\htdocs\joomla\components\com_uddeim\uddeim.php on line 240

Warning: Undefined variable $unreadstr in C:\xampp\htdocs\joomla\components\com_uddeim\uddeim.php on line 242

**Comment by joomod** [comment]
oh yes,
I forgot to add the inbox-postbox switch:
please add (just before line 238)
`if($task =='postbox') {
$unflagtitle = _UDDEIM_STATUS_UNFLAGGED_POSTBOX;
$flagtitle  = _UDDEIM_STATUS_FLAGGED_POSTBOX;
$unreadstr  = _UDDEIM_STATUS_UNREAD_POSTBOX;
} else {
$unflagtitle = _UDDEIM_STATUS_UNFLAGGED;
$flagtitle  = _UDDEIM_STATUS_FLAGGED;
$unreadstr  = _UDDEIM_STATUS_UNREAD;
}`

**Comment by jojo12** [comment]
Yes! Nice! Thanks

**Comment by joomod** [comment]
please go on testing,
in the meanwhile I will update and control the missing templates

**Comment by jojo12** [comment]
fine

**Comment by jojo12** [comment]
Frage: gibt es eine Möglichkeit, dass das "ungelesen" automatisch auf "gelesen" geht, wenn man die Nachricht bewusst anklickt?
Im Moment glaube ich, muss man das "ungelesen" immer selber anklicken.

**Comment by joomod** [comment]
in der inbox ist das ja schon immer so,
und in der postbox habe ich das jetzt ja so programmiert,
dass eine ungelsenene Nachricht immer geschlossen (collapsed)
in der Liste angezeigt wird. ein Klick zum Öffnen wechselt die Nachricht
automatisch auf gelesen (sollte jedenfalls so sein)

**Comment by slabbi** [comment]
Wäre das nicht besser konfigurierbar? Altes/Neues Verhalten?

**Comment by joomod** [comment]
wie meinst du das?

**Comment by jojo12** [comment]
in der Inbox ist es super.
in der Postbox (ich testete zuerst default und flatlook) kann ich die Nachricht noch so oft anklicken, das gelesen kommt nie!
Ich muss immer explizit auf das "unread" klicken, damit sich was ändert.

**Comment by joomod** [comment]
das mit dem umschalten auf gelesen funktioniert nur, 
wenn du die userbox **neu** geöffnet hast.
wenn du die Nachricht als ungelesen markierst, kannst du
das auch nur durch einen Icon-Klick rückgängig machen

**Comment by jojo12** [comment]
was ist userbox?
wie komm ich in den Inspector?
es geht bei mir nur auf gelesen, wenn ich direkt auf die Flag klicke.

**Comment by joomod** [comment]
> was ist userbox?
wenn du in der postbox auf einen user klickst (öffnest)

> wie komm ich in den Inspector?
weis nicht, welchen browser verwendest du?
(in FF rechtsklick -> untersuchen)

**Comment by jojo12** [comment]
![grafik](https://github.com/slabbi/uddeIM/assets/2960236/79b037d1-776b-4111-b743-be191ece7e02)
es verändert sich nichts

**Comment by joomod** [comment]
hmm, 
ich hab die files gerade in ein install zip gepackt und neu installiert
läuft alles wie es soll 
??

**Comment by joomod** [comment]
auf folks-tanz hast du aber die **neuen Dateien** noch nicht überspielt!

die Nachricht enthält den link: javascript:uddeIMtoggleLayer2("1");
toggleLayer2 ist die alte, orig. Version
auch müßte dir auffallen, dass beim klick auf das icon die Seite neu
geladen wird, was bei der neuen Version nicht mehr ist

**Comment by jojo12** [comment]
Ich installierte die gestern von dir in den main branch geladene, ich dachte, das sei die aktuelle

**Comment by joomod** [comment]
die  aus dem zip file hier **oben**

**Comment by jojo12** [comment]
sorry, das war ein Riesenmissverständnis! habs nun und nur files hochladen

**Comment by joomod** [comment]
na bestens,
ich überprüfe gerade noch die übrigen templates
(ist müsig, jede template mit und ohne postbox, sowohl in casiopaia als auch mein allrounder).
bin jetzt 3 Tage offline - also keine Antwort erwarten  :)

**Comment by jojo12** [comment]
auf einer Seite klappts, auf 2 Seiten folgendes: (getestet mit flatlook)
Meldung: neue Nachricht, ungelesen und neu (blinkt)
öffne Postbox, klicke auf usernamen, PM öffnet sich
klicke PM an, -> gelesen, blinkt nicht mehr
klicke auf Postbox (Unterhaltungen): -> wechselt auf ungelesen und neu (blinkt) -->dürfte nicht sein!
usw.

**Comment by joomod** [comment]
> dürfte nicht sein!

ja stimmt,  - sind die Seiten online?
klingt fast so als ob das Ajax (genauer fetch) nicht komplett ausgeführt wird

**Comment by jojo12** [comment]
für eine Seite, die nicht funktioniert, hab ich dir Tempzugang geschickt.

**Comment by joomod** [comment]
hab geschau, aber leider komme ich irgendwie nichts in Frontend
(Registrierung noch nicht abgeschlossen ??)

was ich gesehen habe ist, dass Du **überschreibe ItemId** aktiviert hast und dann 
im ID Feld aber eine Null steht

das geht in die Richtung meiner Vermutung, dass er für die Fetch Anweising
eine URL generiert die nicht existiert, und dann wird der datenbank Eintrag nicht ausgeführt

**Comment by jojo12** [comment]
Daran kanns nicht gelegen haben. Das war nur eine testende Angleichung (aber die 0 war falsch), aber auch bei NEIN geht es nicht.
Ich habe nun die Registrierung im Frontend zugelassen (admin muss allerdings bestätigen).

**Comment by joomod** [comment]
ich bekomme immer noch die Meldung:
Registrierung noch nicht abgeschlossen.
in der email steht:
email wurde bereits bestätigt 
Ist die E-Mail-Adresse bestätigt werden unsere Moderatoren benachrichtigt,
um den Aktivierungsprozess abzuschließen.

**Comment by jojo12** [comment]
Ich hab's gefunden: Komisch-obwohl kein Menüeintrag vorhanden, kam ich immer in die Postbox.
Ich hab jetzt einen Schattenmenüeintrag gemacht und die ID eingetragen, schon klappts!

**Comment by joomod** [comment]
geht's auf beiden Seiten jetzt?

**Comment by jojo12** [comment]
YESSSS! ;-)
it needs a menu point!

**Comment by slabbi** [comment]
Bitte eine Ergänzung zum Manual anlegen, wo die Neuerungen mit den möglichen Problemen (hier: notwendiger Menüeintrag) aufgeführt werden. Sonst hat der nächste dieselben Probleme und weiß nicht weiter.

**Comment by joomod** [comment]
ich schreibe es als Ergänzung zum Config header
denn wer liest schon das Manual :)

**Comment by joomod** [comment]
now I have (hopefully :) finished all template css files,
so the whole package with language, js and new files can be added to the main.
(I also added a note to the config header if no menu itemid is found)

please update the main branch with these files 
and I think it is worth to give a new release (5.5)

[com_uddeim_j50newfiles.zip](https://github.com/user-attachments/files/16052787/com_uddeim_j50newfiles.zip)

**Comment by slabbi** [comment]
uploaded
please do a final check before a new release is created

**Comment by jojo12** [comment]
Nun merke ich, dass das RESTORE meiner alten Einstellung nicht funktioniert hat, der Email-Stop war zwar weg, aber die E-Mail-Einstellungen sind anders als vorher! (Wichtig zu wissen)
vorher: Emailbenachrichtigung in jedem Fall und mit Nachricht
jetzt: Emailbenachrichtigung ja, keine Benachrichtigung als Standard und keine Nachricht

**Comment by joomod** [comment]
ich schau mal ob ich das nachvollziehen kann.
kann aber mit dem update nichts zu tun haben, da ich ja nur
reload links durch JS ersetzt habe.

das mit dem restore muß ich mal genauer anschauen.
wenn es ein update war müßte das script eigentlich ein **backup der config**
erstellt haben.
wann hast du denn die config gesichert?

**Comment by jojo12** [comment]
Sicherung: jedes mal, wenn ich com installierte, habe ich restore verwendet und dann nach cache clean wieder backup gewählt.

**Comment by jojo12** [comment]
Bei der vorherigen version(newfiles mit menü): habe ich diese fehlermeldung nie erhalten! kommt auch im default template

**Comment by joomod** [comment]
mir ist gerade eingefallen, dass ich ja das sql query geändert habe 
um links für die postbox zu erstellen - da könnte der count Fehler herkommen.
ich such mal
(das wiederum hat nichts mit dem restore zu tun)

**Comment by jojo12** [comment]
Ich glaube nicht, dass ich das restore einmal vergessen habe, denn ich habe nie anders den emailstop beendet!

**Comment by jojo12** [comment]
gleiche fehlermeldung auch bei "Weiterleitung"

**Comment by joomod** [comment]
ist das bei der 'online' Seite wo ich mir es mal anschauen könnte?

**Comment by joomod** [comment]
wie wird denn der fehler angezeigt (white page  oder meldung?) ?

**Comment by joomod** [comment]
hattest du das senden vor heute, also mit den 'newfiles' auch mal probiert?

**Comment by jojo12** [comment]
ups: könnte das mit einer Abwesenheitsmeldung des admin zu tun haben? dann kam aber keine Meldung.
Ich habe die Abwesenheitsmeldung entfernt, nun konnte ich senden.

**Comment by slabbi** [comment]
Auch wenn eine Abwesenheitsmeldung eingestellt ist, kann der User nach Nachrichten senden.

**Comment by jojo12** [comment]
Hatte noch nie die Abwesenheitsmeldung probiert. Angestellt und nicht weiter getestet. So merkte ich es erst jetzt.

**Comment by joomod** [comment]
ok danke, jetzt weis ich wenigstens wo ich suchen muß.
hast du bei der Fehlermeldung irgend eine Zeilennummer?

**Comment by jojo12** [comment]
1136 Column count doesn't match value count at row 1

**Comment by jojo12** [comment]
Schau bei #100

**Comment by joomod** [comment]
hast Du mal getestet ob der Fehler auch bei IN/OUTbox Einstellung auftritt?

**Comment by joomod** [comment]
probiers mal....mit der Änderung von slabbi

[uddeim.zip](https://github.com/user-attachments/files/16057556/uddeim.zip)

**Comment by jojo12** [comment]
Gut.
Habe neu installiert. Alles gut, auch restore.
Can be closed.

**Comment by joomod** [comment]
as there are no issues reported I think we (you) can release v.5.5.
see discussion   [https://github.com/slabbi/uddeIM/discussions/101](url)

**Comment by slabbi** [comment]
Have you tested the install? Fresh install and update install works?

**Comment by slabbi** [comment]
- Version strings updated
- iGoogle.xml removed (finally)

**Comment by joomod** [comment]
I tested on 5.3. - nothing changed in script since that

**Comment by slabbi** [comment]
5.5 has been released.

According testing:
Do _always_ test a final release, Even when you have tested a ten earlier versions, redo the testing. You never know. Repeat all test. Installation, updating, removing with re-installation etc. Test the new functions again.

Testing... Testing... Testing... :)

**Comment by joomod** [comment]
ok, I will remember :)
I also updated the uddeim_update.xml in the main
